import codecs

# Read the content from a separate file to avoid PowerShell escaping issues
yaml_content = (
    "# Answer DTOs\n\n"
    "AnswerRequest:\n"
    "  type: object\n"
    "  required: [questionId, selectedOptionId, responseTimeMs]\n"
    "  properties:\n"
    "    questionId:\n"
    "      $ref: 'common.yaml#/UUID'\n"
    "      description: ID of the question being answered\n"
    "    selectedOptionId:\n"
    "      $ref: 'common.yaml#/UUID'\n"
    "      description: ID of the selected option (generated on-the-fly, not persisted)\n"
    "    selectedFormIast:\n"
    "      type: string\n"
    "      description: IAST of the selected form (optional, for declension questions)\n"
    "    responseTimeMs:\n"
    "      type: integer\n"
    "      description: Time taken to answer in milliseconds\n"
    "      minimum: 0\n"
    "\n"
    "AnswerResponse:\n"
    "  type: object\n"
    "  required: [isCorrect, correctAnswerText, questionNumber, totalQuestions]\n"
    "  properties:\n"
    "    isCorrect:\n"
    "      type: boolean\n"
    "      description: Whether the submitted answer was correct\n"
    "    correctOptionId:\n"
    "      $ref: 'common.yaml#/UUID'\n"
    "      description: ID of the correct option (may be null for form-based questions)\n"
    "    correctAnswerText:\n"
    "      type: string\n"
    "      description: The correct answer text (IAST or translation)\n"
    "    explanationRu:\n"
    "      type: string\n"
    "      description: Russian explanation for the correct answer\n"
    "    explanationEn:\n"
    "      type: string\n"
    "      description: English explanation for the correct answer\n"
    "    questionNumber:\n"
    "      type: integer\n"
    "      description: Number of the question that was answered\n"
    "    totalQuestions:\n"
    "      type: integer\n"
    "      description: Total number of questions in the session\n"
    "\n"
    "CompleteSessionResponse:\n"
    "  type: object\n"
    "  required: [sessionId, score, totalQuestions, durationMs]\n"
    "  properties:\n"
    "    sessionId:\n"
    "      $ref: 'common.yaml#/UUID'\n"
    "    score:\n"
    "      type: integer\n"
    "      description: Final score achieved\n"
    "    totalQuestions:\n"
    "      type: integer\n"
    "      description: Total number of questions in the session\n"
    "    durationMs:\n"
    "      type: integer\n"
    "      description: Session duration in milliseconds\n"
    "\n"
    "QuizProgressDto:\n"
    "  type: object\n"
    "  required: [sessionId, answeredQuestions, totalQuestions, found]\n"
    "  properties:\n"
    "    sessionId:\n"
    "      $ref: 'common.yaml#/UUID'\n"
    "    answeredQuestions:\n"
    "      type: integer\n"
    "    totalQuestions:\n"
    "      type: integer\n"
    "    found:\n"
    "      type: boolean\n"
    "      description: Whether an in-progress session was found\n"
    "\n"
    "AnswerHistoryDto:\n"
    "  type: object\n"
    "  required: [questionId, questionText, isCorrect, answeredAt]\n"
    "  properties:\n"
    "    questionId:\n"
    "      $ref: 'common.yaml#/UUID'\n"
    "    questionText:\n"
    "      type: string\n"
    "      description: The question text\n"
    "    selectedAnswerIast:\n"
    "      type: string\n"
    "      description: IAST text of the answer selected by the user\n"
    "    correctOptionIast:\n"
    "      type: string\n"
    "      description: IAST text of the correct answer\n"
    "    isCorrect:\n"
    "      type: boolean\n"
    "      description: Whether the answer was correct\n"
    "    responseTimeMs:\n"
    "      type: integer\n"
    "      description: Time taken to answer in milliseconds\n"
    "    answeredAt:\n"
    "      type: string\n"
    "      format: date-time\n"
    "      description: When the answer was submitted\n"
    "    explanationRu:\n"
    "      type: string\n"
    "      description: Russian explanation for the correct answer\n"
    "    explanationEn:\n"
    "      type: string\n"
    "      description: English explanation for the correct answer\n"
    "\n"
    "QuizSummaryDto:\n"
    "  type: object\n"
    "  required: [sessionId, lessonId, slug, lessonType, score, totalQuestions, status, startedAt]\n"
    "  properties:\n"
    "    sessionId:\n"
    "      $ref: 'common.yaml#/UUID'\n"
    "    lessonId:\n"
    "      $ref: 'common.yaml#/UUID'\n"
    "    lessonTitle:\n"
    "      type: string\n"
    "    lessonTitleRu:\n"
    "      type: string\n"
    "    lessonTitleEn:\n"
    "      type: string\n"
    "    slug:\n"
    "      type: string\n"
    "    lessonType:\n"
    "      $ref: 'common.yaml#/LessonType'\n"
    "    score:\n"
    "      type: integer\n"
    "    totalQuestions:\n"
    "      type: integer\n"
    "    status:\n"
    "      $ref: 'common.yaml#/SessionStatus'\n"
    "    startedAt:\n"
    "      type: string\n"
    "      format: date-time\n"
    "    completedAt:\n"
    "      type: string\n"
    "      format: date-time\n"
    "      nullable: true\n"
    "    durationMs:\n"
    "      type: integer\n"
    "      nullable: true\n"
    "\n"
    "PageQuizSummaryDto:\n"
    "  type: object\n"
    "  required: [content, totalPages, totalElements, number, size]\n"
    "  properties:\n"
    "    content:\n"
    "      type: array\n"
    "      description: List of quiz summaries on this page\n"
    "      items:\n"
    "        $ref: '#/QuizSummaryDto'\n"
    "    totalPages:\n"
    "      type: integer\n"
    "      description: Total number of pages\n"
    "    totalElements:\n"
    "      type: integer\n"
    "      description: Total number of elements across all pages\n"
    "    number:\n"
    "      type: integer\n"
    "      description: Current page number (0-based)\n"
    "    size:\n"
    "      type: integer\n"
    "      description: Page size\n"
    "    numberOfElements:\n"
    "      type: integer\n"
    "      description: Number of elements on this page\n"
    "    first:\n"
    "      type: boolean\n"
    "      description: Whether this is the first page\n"
    "    last:\n"
    "      type: boolean\n"
    "      description: Whether this is the last page\n"
    "    sort:\n"
    "      type: object\n"
    "      properties:\n"
    "        sorted:\n"
    "          type: boolean\n"
    "        unsorted:\n"
    "          type: boolean\n"
    "        empty:\n"
    "          type: boolean\n"
)

encoded = codecs.encode(yaml_content, 'utf-16-le')
bom = b'\xff\xfe'
full = bom + encoded

with open('docs/openapi/quiz/schemas/answers.yaml', 'wb') as f:
    f.write(full)

print('Done, wrote ' + str(len(full)) + ' bytes')