server:
  port: ${AUTH_SERVICE_PORT}

spring:
  application:
    name: auth-service
  config:
    import: "optional:file:.env[.properties]"
  threads:
    virtual:
      enabled: true

keycloak:
  url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
