-- Seed of 70 atomic GRAMMAR topics (L0-L6) + 2 evergreen topics.
-- Source layout: curriculum.md §2 / curriculum-service.md §3 (~70 rows, uneven by level).
-- Matches the actual schema (V1): no `domain` column here.

INSERT INTO curriculum.topic (id, code, title_ru, title_en, learning_level, is_evergreen, display_order) VALUES
    -- L0 — Devanāgarī, phonetics, first words (8 topics)
    (gen_random_uuid(), 'deva-svara', 'Devanāgarī: гласные (svara)', 'Devanāgarī: vowels (svara)', 'L0', false, 1),
    (gen_random_uuid(), 'deva-vyanjana', 'Devanāgarī: согласные (vyañjana)', 'Devanāgarī: consonants (vyañjana)', 'L0', false, 2),
    (gen_random_uuid(), 'matra-conjuncts', 'Mātrā и сочетания согласных', 'Mātrā and consonant clusters', 'L0', false, 3),
    (gen_random_uuid(), 'deva-diacritics', 'Anusvāra, visarga, chandrabindu', 'Anusvāra, visarga, chandrabindu', 'L0', false, 4),
    (gen_random_uuid(), 'articulation-places', 'Места и способы артикуляции', 'Places and manners of articulation', 'L0', false, 5),
    (gen_random_uuid(), 'vowel-length-oppositions', 'Долгие и краткие гласные', 'Long and short vowels', 'L0', false, 6),
    (gen_random_uuid(), 'basic-function-words', 'Базовые служебные слова', 'Basic function words', 'L0', false, 7),
    (gen_random_uuid(), 'basic-vocabulary-core', 'Базовая лексика', 'Core vocabulary', 'L0', false, 8),

    -- L1 — sandhi, a-stems, pronouns, verb anatomy (11 topics)
    (gen_random_uuid(), 'sandhi-vowels-external', 'Sandhi: внешние гласные', 'Sandhi: external vowel sandhi', 'L1', false, 1),
    (gen_random_uuid(), 'sandhi-consonants', 'Sandhi: согласные', 'Sandhi: consonant sandhi', 'L1', false, 2),
    (gen_random_uuid(), 'sandhi-visarga', 'Sandhi: visarga', 'Sandhi: visarga', 'L1', false, 3),
    (gen_random_uuid(), 'stem-case-concept', 'Основа, окончание, падеж', 'Stem, ending, and case', 'L1', false, 4),
    (gen_random_uuid(), 'a-stem-masc', 'a-основы: мужской род', 'a-stems: masculine', 'L1', false, 5),
    (gen_random_uuid(), 'a-stem-neut', 'a-основы: средний род', 'a-stems: neuter', 'L1', false, 6),
    (gen_random_uuid(), 'a-stem-fem', 'ā-основы: женский род', 'ā-stems: feminine', 'L1', false, 7),
    (gen_random_uuid(), 'case-meanings-basic', 'Основные значения падежей', 'Basic case meanings', 'L1', false, 8),
    (gen_random_uuid(), 'personal-pronouns', 'Личные местоимения', 'Personal pronouns', 'L1', false, 9),
    (gen_random_uuid(), 'pronoun-stems-declension', 'Склонение местоимений', 'Pronoun stem declension', 'L1', false, 10),
    (gen_random_uuid(), 'verb-root-stem-ending', 'Корень, основа, окончание глагола', 'Verb root, stem, and ending', 'L1', false, 11),

    -- L2 — present tense, i/u/ṛ-stems, pronouns, sentence (10 topics)
    (gen_random_uuid(), 'present-parasmaipada-formation', 'Present: parasmaipada (образование)', 'Present tense: parasmaipada formation', 'L2', false, 1),
    (gen_random_uuid(), 'present-parasmaipada-usage', 'Present: parasmaipada (употребление)', 'Present tense: parasmaipada usage', 'L2', false, 2),
    (gen_random_uuid(), 'present-atmanepada', 'Present: ātmanepada', 'Present tense: ātmanepada', 'L2', false, 3),
    (gen_random_uuid(), 'i-u-stems', 'i/u-основы', 'i/u-stems', 'L2', false, 4),
    (gen_random_uuid(), 'r-stems', 'ṛ-основы', 'ṛ-stems', 'L2', false, 5),
    (gen_random_uuid(), 'demonstrative-pronouns', 'Указательные местоимения', 'Demonstrative pronouns', 'L2', false, 6),
    (gen_random_uuid(), 'interrogative-pronouns', 'Вопросительные местоимения', 'Interrogative pronouns', 'L2', false, 7),
    (gen_random_uuid(), 'relative-pronouns', 'Относительные местоимения', 'Relative pronouns', 'L2', false, 8),
    (gen_random_uuid(), 'noun-adjective-agreement', 'Согласование существительного и прилагательного', 'Noun-adjective agreement', 'L2', false, 9),
    (gen_random_uuid(), 'simple-sentence-svo', 'Простое предложение (SOV)', 'Simple sentences: subject-object-verb', 'L2', false, 10),

    -- L3 — numerals, more tenses, participles, absolutive, kāraka (12 topics)
    (gen_random_uuid(), 'numerals-1-4', 'Числительные 1–4', 'Numerals 1–4', 'L3', false, 1),
    (gen_random_uuid(), 'numerals-5-10', 'Числительные 5–10', 'Numerals 5–10', 'L3', false, 2),
    (gen_random_uuid(), 'numeral-agreement', 'Числительные: согласование', 'Numeral agreement', 'L3', false, 3),
    (gen_random_uuid(), 'imperfect', 'Imperfect (laṅ)', 'Imperfect tense (laṅ)', 'L3', false, 4),
    (gen_random_uuid(), 'future', 'Future (lṛṭ)', 'Future tense (lṛṭ)', 'L3', false, 5),
    (gen_random_uuid(), 'verb-root-classes-overview', 'Классы глагольных корней', 'Verb root classes', 'L3', false, 6),
    (gen_random_uuid(), 'present-active-participle', 'Present active participle', 'Present active participle', 'L3', false, 7),
    (gen_random_uuid(), 'past-passive-participle', 'Past passive participle (kta)', 'Past passive participle (kta)', 'L3', false, 8),
    (gen_random_uuid(), 'absolutive-ktva', 'Абсолютив: ktvā', 'Absolutives: ktvā', 'L3', false, 9),
    (gen_random_uuid(), 'absolutive-ya', 'Абсолютив: -ya', 'Absolutives: -ya (lyap)', 'L3', false, 10),
    (gen_random_uuid(), 'karaka-semantic-roles', 'Kāraka и семантические роли', 'Kāraka and semantic roles', 'L3', false, 11),
    (gen_random_uuid(), 'case-as-karaka', 'Падежи как kāraka', 'Cases as kāraka', 'L3', false, 12),

    -- L4 — perfect/aorist/imperative/optative, participles, syntax (11 topics)
    (gen_random_uuid(), 'perfect', 'Perfect (liṭ)', 'Perfect tense (liṭ)', 'L4', false, 1),
    (gen_random_uuid(), 'aorist', 'Aorist (luṅ)', 'Aorist (luṅ)', 'L4', false, 2),
    (gen_random_uuid(), 'imperative', 'Imperative (loṭ)', 'Imperative mood (loṭ)', 'L4', false, 3),
    (gen_random_uuid(), 'optative', 'Optative (vidhiliṅ)', 'Optative mood (vidhiliṅ)', 'L4', false, 4),
    (gen_random_uuid(), 'participle-past-active', 'Причастие: past active', 'Participles: past active', 'L4', false, 5),
    (gen_random_uuid(), 'participle-future', 'Причастие: future', 'Participles: future', 'L4', false, 6),
    (gen_random_uuid(), 'participial-constructions', 'Причастные обороты', 'Participial constructions', 'L4', false, 7),
    (gen_random_uuid(), 'irregular-stems-declension', 'Сложные и нестандартные склонения', 'Irregular stems and declensions', 'L4', false, 8),
    (gen_random_uuid(), 'relative-constructions', 'Относительные конструкции (yad–tad)', 'Relative constructions (yad–tad)', 'L4', false, 9),
    (gen_random_uuid(), 'correlative-constructions', 'Коррелятивные конструкции', 'Correlative constructions', 'L4', false, 10),
    (gen_random_uuid(), 'complex-noun-phrases', 'Сложные именные группы', 'Complex noun phrases', 'L4', false, 11),

    -- L5 — compounds, derivation, complex clauses (10 topics)
    (gen_random_uuid(), 'compound-words-basics', 'Сложные слова: основы', 'Compound words: basics', 'L5', false, 1),
    (gen_random_uuid(), 'tatpurusha', 'Tatpuruṣa', 'Tatpuruṣa compounds', 'L5', false, 2),
    (gen_random_uuid(), 'karmadharaya', 'Karmadhāraya', 'Karmadhāraya compounds', 'L5', false, 3),
    (gen_random_uuid(), 'bahuvrihi', 'Bahuvrīhi', 'Bahuvrīhi compounds', 'L5', false, 4),
    (gen_random_uuid(), 'dvandva', 'Dvandva', 'Dvandva compounds', 'L5', false, 5),
    (gen_random_uuid(), 'derivation-tva-ta', 'Словообразование: -tva, -ta', 'Derivation: -tva, -ta', 'L5', false, 6),
    (gen_random_uuid(), 'derivation-in-vant-mat', 'Словообразование: -in, -vant, -mat', 'Derivation: -in, -vant, -mat', 'L5', false, 7),
    (gen_random_uuid(), 'conditional-constructions', 'Условные конструкции', 'Conditional constructions', 'L5', false, 8),
    (gen_random_uuid(), 'reported-speech', 'Косвенная речь', 'Reported speech', 'L5', false, 9),
    (gen_random_uuid(), 'complex-subordinate-clauses', 'Сложные придаточные предложения', 'Complex subordinate clauses', 'L5', false, 10),

    -- L6 — synthesis, complex syntax, analysis (8 topics)
    (gen_random_uuid(), 'complex-sandhi-combinations', 'Сложные комбинации sandhi', 'Complex sandhi combinations', 'L6', false, 1),
    (gen_random_uuid(), 'irregular-rare-forms', 'Редкие и нерегулярные формы', 'Irregular and rare forms', 'L6', false, 2),
    (gen_random_uuid(), 'complex-verb-constructions', 'Сложные глагольные конструкции', 'Complex verb constructions', 'L6', false, 3),
    (gen_random_uuid(), 'absolute-constructions', 'Абсолютные конструкции', 'Absolute constructions', 'L6', false, 4),
    (gen_random_uuid(), 'complex-relative-constructions', 'Сложные относительные конструкции', 'Complex relative constructions', 'L6', false, 5),
    (gen_random_uuid(), 'poetic-word-order', 'Поэтический порядок слов', 'Poetic word order', 'L6', false, 6),
    (gen_random_uuid(), 'ellipsis-implied-forms', 'Эллипсис и подразумеваемые формы', 'Ellipsis and implied forms', 'L6', false, 7),
    (gen_random_uuid(), 'syntactic-analysis-of-text', 'Синтаксический разбор текста', 'Syntactic analysis of original text', 'L6', false, 8),

    -- Evergreen — outside levels and graph (display_order NULL)
    (gen_random_uuid(), 'mixed-review', 'Mixed review', 'Mixed review', 'L0', true, NULL),
    (gen_random_uuid(), 'error-correction', 'Error correction', 'Error correction', 'L0', true, NULL);

-- Prerequisite edges (RECOMMENDED strength, see curriculum.md §1). All seeded
-- topics are GRAMMAR, so the join is on code only (no `domain` column in V1).
INSERT INTO curriculum.topic_prerequisite (topic_id, prerequisite_topic_id, strength)
SELECT t.id, p.id, 'RECOMMENDED'
FROM (VALUES
    ('deva-vyanjana', 'deva-svara'),
    ('matra-conjuncts', 'deva-vyanjana'),
    ('deva-diacritics', 'matra-conjuncts'),
    ('articulation-places', 'deva-vyanjana'),
    ('vowel-length-oppositions', 'deva-svara'),
    ('basic-vocabulary-core', 'basic-function-words'),
    ('sandhi-vowels-external', 'deva-svara'),
    ('sandhi-consonants', 'sandhi-vowels-external'),
    ('sandhi-visarga', 'sandhi-consonants'),
    ('sandhi-visarga', 'deva-diacritics'),
    ('stem-case-concept', 'basic-vocabulary-core'),
    ('a-stem-masc', 'stem-case-concept'),
    ('a-stem-neut', 'a-stem-masc'),
    ('a-stem-fem', 'a-stem-masc'),
    ('case-meanings-basic', 'a-stem-masc'),
    ('personal-pronouns', 'a-stem-masc'),
    ('pronoun-stems-declension', 'personal-pronouns'),
    ('verb-root-stem-ending', 'basic-vocabulary-core'),
    ('present-parasmaipada-formation', 'verb-root-stem-ending'),
    ('present-parasmaipada-usage', 'present-parasmaipada-formation'),
    ('present-atmanepada', 'present-parasmaipada-formation'),
    ('i-u-stems', 'a-stem-neut'),
    ('i-u-stems', 'a-stem-fem'),
    ('r-stems', 'i-u-stems'),
    ('demonstrative-pronouns', 'pronoun-stems-declension'),
    ('interrogative-pronouns', 'pronoun-stems-declension'),
    ('relative-pronouns', 'demonstrative-pronouns'),
    ('noun-adjective-agreement', 'a-stem-fem'),
    ('noun-adjective-agreement', 'case-meanings-basic'),
    ('simple-sentence-svo', 'present-parasmaipada-usage'),
    ('simple-sentence-svo', 'noun-adjective-agreement'),
    ('numerals-1-4', 'demonstrative-pronouns'),
    ('numerals-5-10', 'numerals-1-4'),
    ('numeral-agreement', 'numerals-5-10'),
    ('numeral-agreement', 'noun-adjective-agreement'),
    ('imperfect', 'present-parasmaipada-usage'),
    ('future', 'present-parasmaipada-usage'),
    ('verb-root-classes-overview', 'present-atmanepada'),
    ('present-active-participle', 'present-parasmaipada-formation'),
    ('past-passive-participle', 'verb-root-classes-overview'),
    ('absolutive-ktva', 'present-parasmaipada-usage'),
    ('absolutive-ya', 'absolutive-ktva'),
    ('karaka-semantic-roles', 'simple-sentence-svo'),
    ('case-as-karaka', 'karaka-semantic-roles'),
    ('perfect', 'imperfect'),
    ('aorist', 'imperfect'),
    ('imperative', 'present-parasmaipada-usage'),
    ('optative', 'present-parasmaipada-usage'),
    ('participle-past-active', 'past-passive-participle'),
    ('participle-future', 'future'),
    ('participle-future', 'present-active-participle'),
    ('participial-constructions', 'participle-past-active'),
    ('participial-constructions', 'karaka-semantic-roles'),
    ('irregular-stems-declension', 'r-stems'),
    ('relative-constructions', 'relative-pronouns'),
    ('relative-constructions', 'case-as-karaka'),
    ('correlative-constructions', 'relative-constructions'),
    ('complex-noun-phrases', 'noun-adjective-agreement'),
    ('complex-noun-phrases', 'irregular-stems-declension'),
    ('compound-words-basics', 'complex-noun-phrases'),
    ('tatpurusha', 'compound-words-basics'),
    ('karmadharaya', 'compound-words-basics'),
    ('bahuvrihi', 'compound-words-basics'),
    ('dvandva', 'compound-words-basics'),
    ('derivation-tva-ta', 'past-passive-participle'),
    ('derivation-in-vant-mat', 'derivation-tva-ta'),
    ('conditional-constructions', 'optative'),
    ('conditional-constructions', 'correlative-constructions'),
    ('reported-speech', 'simple-sentence-svo'),
    ('complex-subordinate-clauses', 'correlative-constructions'),
    ('complex-subordinate-clauses', 'participial-constructions'),
    ('complex-sandhi-combinations', 'sandhi-visarga'),
    ('irregular-rare-forms', 'irregular-stems-declension'),
    ('irregular-rare-forms', 'perfect'),
    ('complex-verb-constructions', 'aorist'),
    ('complex-verb-constructions', 'optative'),
    ('absolute-constructions', 'participial-constructions'),
    ('complex-relative-constructions', 'correlative-constructions'),
    ('poetic-word-order', 'complex-subordinate-clauses'),
    ('ellipsis-implied-forms', 'poetic-word-order'),
    ('syntactic-analysis-of-text', 'ellipsis-implied-forms'),
    ('syntactic-analysis-of-text', 'complex-verb-constructions')
) AS e(topic_code, prerequisite_code)
JOIN curriculum.topic t ON t.code = e.topic_code
JOIN curriculum.topic p ON p.code = e.prerequisite_code;
