-- V35: conjugation paradigms for the presence-indicativus lesson.
-- Present-tense example sentences (person x number = 9 per verb) for the verb
-- lesson presence-indicativus. Source: etcetera/grammar/sanskrit_verbs_present.json.
-- Served by ConjugationParadigmService as an index-based carousel (one verb per page).

CREATE TABLE curriculum.conjugation_forms (
    id                  UUID PRIMARY KEY,
    topic_code          VARCHAR(80)  NOT NULL,
    lemma_iast          VARCHAR(120) NOT NULL,
    lemma_devanagari    VARCHAR(120),
    meaning_ru          VARCHAR(200),
    voice               VARCHAR(40)  NOT NULL,
    person              INT          NOT NULL CHECK (person IN (1, 2, 3)),
    number_type         VARCHAR(40)  NOT NULL,
    sentence_iast       VARCHAR(300) NOT NULL,
    sentence_devanagari VARCHAR(300) NOT NULL,
    translation_ru      VARCHAR(300) NOT NULL,
    CONSTRAINT uq_conjugation_forms UNIQUE (topic_code, lemma_iast, voice, person, number_type)
);

COMMENT ON TABLE curriculum.conjugation_forms IS
    'Present-tense conjugation paradigm cells (example sentences, person x number) for verb lessons.';

INSERT INTO curriculum.conjugation_forms
    (id, topic_code, lemma_iast, lemma_devanagari, meaning_ru, voice, person, number_type, sentence_iast, sentence_devanagari, translation_ru)
VALUES
  (gen_random_uuid(), 'presence-indicativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ sukhī bhavāmi.', 'अहम् सुखी भवामि।', 'Я становлюсь счастливым.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 1, 'DUAL', 'Āvām sukhinau bhavāvaḥ.', 'आवाम् सुखिनौ भवावः।', 'Мы вдвоем становимся счастливыми.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam sukhinaḥ bhavāmaḥ.', 'वयम् सुखिनः भवामः।', 'Мы становимся счастливыми.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam sukhī bhavasi.', 'त्वम् सुखी भवसि।', 'Ты становишься счастливым.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām sukhinau bhavathaḥ.', 'युवाम् सुखिनौ भवथः।', 'Вы вдвоем становитесь счастливыми.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam sukhinaḥ bhavatha.', 'यूयम् सुखिनः भवथ।', 'Вы становитесь счастливыми.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 3, 'SINGULAR', 'Bālaḥ sukhī bhavati.', 'बालः सुखी भवति।', 'Мальчик становится счастливым.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 3, 'DUAL', 'Bālau sukhinau bhavataḥ.', 'बालौ सुखिनौ भवतः।', 'Двое мальчиков становятся счастливыми.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 3, 'PLURAL', 'Bālāḥ sukhinaḥ bhavanti.', 'बालाः सुखिनः भवन्ति।', 'Мальчики становятся счастливыми.'),
  (gen_random_uuid(), 'presence-indicativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ pustakaṁ paṭhāmi.', 'अहम् पुस्तकम् पठामि।', 'Я читаю книгу.'),
  (gen_random_uuid(), 'presence-indicativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 1, 'DUAL', 'Āvām pustakaṁ paṭhāvaḥ.', 'आवाम् पुस्तकम् पठावः।', 'Мы вдвоем читаем книгу.'),
  (gen_random_uuid(), 'presence-indicativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam pustakaṁ paṭhāmaḥ.', 'वयम् पुस्तकम् पठामः।', 'Мы читаем книгу.'),
  (gen_random_uuid(), 'presence-indicativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam pustakaṁ paṭhasi.', 'त्वम् पुस्तकम् पठसि।', 'Ты читаешь книгу.'),
  (gen_random_uuid(), 'presence-indicativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām pustakaṁ paṭhathaḥ.', 'युवाम् पुस्तकम् पठथः।', 'Вы вдвоем читаете книгу.'),
  (gen_random_uuid(), 'presence-indicativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam pustakaṁ paṭhatha.', 'यूयम् पुस्तकम् पठथ।', 'Вы читаете книгу.'),
  (gen_random_uuid(), 'presence-indicativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 3, 'SINGULAR', 'Chātraḥ pustakaṁ paṭhati.', 'छात्रः पुस्तकम् पठति।', 'Ученик читает книгу.'),
  (gen_random_uuid(), 'presence-indicativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 3, 'DUAL', 'Chātrau pustakaṁ paṭhataḥ.', 'छात्रौ पुस्तकम् पठतः।', 'Двое учеников читают книгу.'),
  (gen_random_uuid(), 'presence-indicativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 3, 'PLURAL', 'Chātrāḥ pustakaṁ paṭhanti.', 'छात्राः पुस्तकम् पठन्ति।', 'Ученики читают книгу.'),
  (gen_random_uuid(), 'presence-indicativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ gṛhaṁ gacchāmi.', 'अहम् गृहम् गच्छामि।', 'Я иду домой.'),
  (gen_random_uuid(), 'presence-indicativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 1, 'DUAL', 'Āvām gṛhaṁ gacchāvaḥ.', 'आवाम् गृहम् गच्छावः।', 'Мы вдвоем идем домой.'),
  (gen_random_uuid(), 'presence-indicativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam gṛhaṁ gacchāmaḥ.', 'वयम् गृहम् गच्छामः।', 'Мы идем домой.'),
  (gen_random_uuid(), 'presence-indicativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam gṛhaṁ gacchasi.', 'त्वम् गृहम् गच्छसि।', 'Ты идешь домой.'),
  (gen_random_uuid(), 'presence-indicativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām gṛhaṁ gacchathaḥ.', 'युवाम् गृहम् गच्छथः।', 'Вы вдвоем идете домой.'),
  (gen_random_uuid(), 'presence-indicativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam gṛhaṁ gacchatha.', 'यूयम् गृहम् गच्छथ।', 'Вы идете домой.'),
  (gen_random_uuid(), 'presence-indicativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 3, 'SINGULAR', 'Naraḥ gṛhaṁ gacchati.', 'नरः गृहम् गच्छति।', 'Человек идет домой.'),
  (gen_random_uuid(), 'presence-indicativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 3, 'DUAL', 'Narau gṛhaṁ gacchataḥ.', 'नरौ गृहम् गच्छतः।', 'Двое людей идут домой.'),
  (gen_random_uuid(), 'presence-indicativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 3, 'PLURAL', 'Narāḥ gṛhaṁ gacchanti.', 'नराः गृहम् गच्छन्ति।', 'Люди идут домой.'),
  (gen_random_uuid(), 'presence-indicativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ citraṁ paśyāmi.', 'अहम् चित्रम् पश्यामि।', 'Я вижу картинку.'),
  (gen_random_uuid(), 'presence-indicativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 1, 'DUAL', 'Āvām citraṁ paśyāvaḥ.', 'आवाम् चित्रम् पश्यावः।', 'Мы вдвоем видим картинку.'),
  (gen_random_uuid(), 'presence-indicativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam citraṁ paśyāmaḥ.', 'वयम् चित्रम् पश्यामः।', 'Мы видим картинку.'),
  (gen_random_uuid(), 'presence-indicativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam citraṁ paśyasi.', 'त्वम् चित्रम् पश्यसि।', 'Ты видишь картинку.'),
  (gen_random_uuid(), 'presence-indicativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām citraṁ paśyathaḥ.', 'युवाम् चित्रम् पश्यथः।', 'Вы вдвоем видите картинку.'),
  (gen_random_uuid(), 'presence-indicativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam citraṁ paśyatha.', 'यूयम् चित्रम् पश्यथ।', 'Вы видите картинку.'),
  (gen_random_uuid(), 'presence-indicativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 3, 'SINGULAR', 'Bālaḥ citraṁ paśyati.', 'बालः चित्रम् पश्यति।', 'Мальчик видит картинку.'),
  (gen_random_uuid(), 'presence-indicativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 3, 'DUAL', 'Bālau citraṁ paśyataḥ.', 'बालौ चित्रम् पश्यतः।', 'Двое мальчиков видят картинку.'),
  (gen_random_uuid(), 'presence-indicativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 3, 'PLURAL', 'Bālāḥ citraṁ paśyanti.', 'बालाः चित्रम् पश्यन्ति।', 'Мальчики видят картинку.'),
  (gen_random_uuid(), 'presence-indicativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ patraṁ likhāmi.', 'अहम् पत्रम् लिखामि।', 'Я пишу письмо.'),
  (gen_random_uuid(), 'presence-indicativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 1, 'DUAL', 'Āvām patraṁ likhāvaḥ.', 'आवाम् पत्रम् लिखावः।', 'Мы вдвоем пишем письмо.'),
  (gen_random_uuid(), 'presence-indicativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam patraṁ likhāmaḥ.', 'वयम् पत्रम् लिखामः।', 'Мы пишем письмо.'),
  (gen_random_uuid(), 'presence-indicativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam patraṁ likhasi.', 'त्वम् पत्रम् लिखसि।', 'Ты пишешь письмо.'),
  (gen_random_uuid(), 'presence-indicativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām patraṁ likhathaḥ.', 'युवाम् पत्रम् लिखथः।', 'Вы вдвоем пишете письмо.'),
  (gen_random_uuid(), 'presence-indicativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam patraṁ likhatha.', 'यूयम् पत्रम् लिखथ।', 'Вы пишете письмо.'),
  (gen_random_uuid(), 'presence-indicativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 3, 'SINGULAR', 'Kaviḥ patraṁ likhati.', 'कविः पत्रम् लिखति।', 'Поэт пишет письмо.'),
  (gen_random_uuid(), 'presence-indicativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 3, 'DUAL', 'Kavī patraṁ likhataḥ.', 'कवी पत्रम् लिखतः।', 'Двое поэтов пишут письмо.'),
  (gen_random_uuid(), 'presence-indicativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 3, 'PLURAL', 'Kavayaḥ patraṁ likhanti.', 'कवयः पत्रम् लिखन्ति।', 'Поэты пишут письмо.'),
  (gen_random_uuid(), 'presence-indicativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ dhanaṁ labhe.', 'अहम् धनम् लभे।', 'Я получаю богатство.'),
  (gen_random_uuid(), 'presence-indicativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 1, 'DUAL', 'Āvām dhanaṁ labhāvahaḥ.', 'आवाम् धनम् लभावहे।', 'Мы вдвоем получаем богатство.'),
  (gen_random_uuid(), 'presence-indicativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ dhanaṁ labhāmahe.', 'वयम् धनम् लभामहे।', 'Мы получаем богатство.'),
  (gen_random_uuid(), 'presence-indicativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam dhanaṁ labhase.', 'त्वम् धनम् लभसे।', 'Ты получаешь богатство.'),
  (gen_random_uuid(), 'presence-indicativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 2, 'DUAL', 'Yuvām dhanaṁ labhethe.', 'युवाम् धनम् लभेथे।', 'Вы вдвоем получаете богатство.'),
  (gen_random_uuid(), 'presence-indicativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam dhanaṁ labhadhve.', 'यूयम् धनम् लभध्वे।', 'Вы получаете богатство.'),
  (gen_random_uuid(), 'presence-indicativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 3, 'SINGULAR', 'Naraḥ dhanaṁ labhate.', 'नरः धनम् लभते।', 'Человек получает богатство.'),
  (gen_random_uuid(), 'presence-indicativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 3, 'DUAL', 'Narau dhanaṁ labhete.', 'नरौ धनम् लभेते।', 'Двое людей получают богатство.'),
  (gen_random_uuid(), 'presence-indicativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 3, 'PLURAL', 'Narāḥ dhanaṁ labhante.', 'नराः धनम् लभन्ते।', 'Люди получают богатство.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ satyaṁ bhāṣe.', 'अहम् सत्यम् भाषे।', 'Я говорю правду.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 1, 'DUAL', 'Āvām satyaṁ bhāṣāvahaḥ.', 'आवाम् सत्यम् भाषावहे।', 'Мы вдвоем говорим правду.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ satyaṁ bhāṣāmahe.', 'वयम् सत्यम् भाषामहे।', 'Мы говорим правду.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam satyaṁ bhāṣase.', 'त्वम् सत्यम् भाषसे।', 'Ты говоришь правду.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 2, 'DUAL', 'Yuvām satyaṁ bhāṣethe.', 'युवाम् सत्यम् भाषेथे।', 'Вы вдвоем говорите правду.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam satyaṁ bhāṣadhve.', 'यूयम् सत्यम् भाषध्वे।', 'Вы говорите правду.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 3, 'SINGULAR', 'Bālaḥ satyaṁ bhāṣate.', 'बालः सत्यम् भाषते।', 'Мальчик говорит правду.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 3, 'DUAL', 'Bālau satyaṁ bhāṣete.', 'बालौ सत्यम् भाषेते।', 'Двое мальчиков говорят правду.'),
  (gen_random_uuid(), 'presence-indicativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 3, 'PLURAL', 'Bālāḥ satyaṁ bhāṣante.', 'बालाः सत्यम् भाषन्ते।', 'Мальчики говорят правду.'),
  (gen_random_uuid(), 'presence-indicativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ guruṁ seve.', 'अहम् गुरुम् सेवे।', 'Я служу учителю.'),
  (gen_random_uuid(), 'presence-indicativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 1, 'DUAL', 'Āvām guruṁ sevāvahaḥ.', 'आवाम् गुरुम् सेवावहे।', 'Мы вдвоем служим учителю.'),
  (gen_random_uuid(), 'presence-indicativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ guruṁ sevāmahe.', 'वयम् गुरुम् सेवामहे।', 'Мы служим учителю.'),
  (gen_random_uuid(), 'presence-indicativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam guruṁ sevase.', 'त्वम् गुरुम् सेवसे।', 'Ты служишь учителю.'),
  (gen_random_uuid(), 'presence-indicativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 2, 'DUAL', 'Yuvām guruṁ sevethe.', 'युवाम् गुरुम् सेवेथे।', 'Вы вдвоем служите учителю.'),
  (gen_random_uuid(), 'presence-indicativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam guruṁ sevadhve.', 'यूयम् गुरुम् सेवध्वे।', 'Вы служите учителю.'),
  (gen_random_uuid(), 'presence-indicativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 3, 'SINGULAR', 'Chātraḥ guruṁ sevate.', 'छात्रः गुरुम् सेवते।', 'Ученик служит учителю.'),
  (gen_random_uuid(), 'presence-indicativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 3, 'DUAL', 'Chātrau guruṁ sevete.', 'छात्रौ गुरुम् सेवेते।', 'Двое учеников служат учителю.'),
  (gen_random_uuid(), 'presence-indicativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 3, 'PLURAL', 'Chātrāḥ guruṁ sevante.', 'छात्राः गुरुम् सेवन्ते।', 'Ученики служат учителю.'),
  (gen_random_uuid(), 'presence-indicativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ atra varte.', 'अहम् अत्र वर्ते।', 'Я нахожусь здесь.'),
  (gen_random_uuid(), 'presence-indicativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 1, 'DUAL', 'Āvām atra vartāvahaḥ.', 'आवाम् अत्र वर्तावहे।', 'Мы вдвоем находимся здесь.'),
  (gen_random_uuid(), 'presence-indicativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ atra vartāmahe.', 'वयम् अत्र वर्तामहे।', 'Мы находимся здесь.'),
  (gen_random_uuid(), 'presence-indicativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam atra vartase.', 'त्वम् अत्र वर्तसे।', 'Ты находишься здесь.'),
  (gen_random_uuid(), 'presence-indicativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 2, 'DUAL', 'Yuvām atra vartethe.', 'युवाम् अत्र वर्तेथे।', 'Вы вдвоем находитесь здесь.'),
  (gen_random_uuid(), 'presence-indicativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam atra vartadhve.', 'यूयम् अत्र वर्तध्वे।', 'Вы находитесь здесь.'),
  (gen_random_uuid(), 'presence-indicativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 3, 'SINGULAR', 'Śāntiḥ atra vartate.', 'शान्तिः अत्र वर्तते।', 'Мир находится здесь.'),
  (gen_random_uuid(), 'presence-indicativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 3, 'DUAL', 'Śāntī atra vartete.', 'शान्ती अत्र वर्तेते।', 'Два состояния мира находятся здесь.'),
  (gen_random_uuid(), 'presence-indicativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 3, 'PLURAL', 'Śāntayaḥ atra vartante.', 'शान्तयः अत्र वर्तन्ते।', 'Состояния мира находятся здесь.'),
  (gen_random_uuid(), 'presence-indicativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ sādhu manye.', 'अहम् साधु मन्ये।', 'Я считаю это хорошим.'),
  (gen_random_uuid(), 'presence-indicativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 1, 'DUAL', 'Āvām sādhu manyāvahaḥ.', 'आवाम् साधु मन्यावहे।', 'Мы вдвоем считаем это хорошим.'),
  (gen_random_uuid(), 'presence-indicativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ sādhu manyāmahe.', 'वयम् साधु मन्यामहे।', 'Мы считаем это хорошим.'),
  (gen_random_uuid(), 'presence-indicativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam sādhu manyase.', 'त्वम् साधु मन्यसे।', 'Ты считаешь это хорошим.'),
  (gen_random_uuid(), 'presence-indicativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 2, 'DUAL', 'Yuvām sādhu manyethe.', 'युवाम् साधु मन्येथे।', 'Вы вдвоем считаете это хорошим.'),
  (gen_random_uuid(), 'presence-indicativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam sādhu manyadhve.', 'यूयम् साधु मन्यध्वे।', 'Вы считаете это хорошим.'),
  (gen_random_uuid(), 'presence-indicativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 3, 'SINGULAR', 'Nṛpaḥ sādhu manyate.', 'नृपः साधु मन्यते।', 'Царь считает это хорошим.'),
  (gen_random_uuid(), 'presence-indicativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 3, 'DUAL', 'Nṛpau sādhu manyete.', 'नृपौ साधु मन्येते।', 'Двое царей считают это хорошим.'),
  (gen_random_uuid(), 'presence-indicativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 3, 'PLURAL', 'Nṛpāḥ sādhu manyante.', 'नृपाः साधु मन्यन्ते।', 'Цари считают это хорошим.');
