-- V36: conjugation paradigms for the imperfectum lesson.
-- Imperfect-tense example sentences (person x number = 9 per verb) for the verb
-- lesson imperfectum. Source: etcetera/grammar/sanskrit_verbs_imperfect.json.
-- Served by ConjugationParadigmService as an index-based carousel (one verb per page).

INSERT INTO curriculum.conjugation_forms
    (id, topic_code, lemma_iast, lemma_devanagari, meaning_ru, voice, person, number_type, sentence_iast, sentence_devanagari, translation_ru)
VALUES
  (gen_random_uuid(), 'imperfectum', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ sukhī abhavam.', 'अहम् सुखी अभवम्।', 'Я становился счастливым.'),
  (gen_random_uuid(), 'imperfectum', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 1, 'DUAL', 'Āvām sukhinau abhavāva.', 'आवाम् सुखिनौ अभवाव।', 'Мы вдвоем становились счастливыми.'),
  (gen_random_uuid(), 'imperfectum', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam sukhinaḥ abhavāma.', 'वयम् सुखिनः अभवाम।', 'Мы становились счастливыми.'),
  (gen_random_uuid(), 'imperfectum', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam sukhī abhavaḥ.', 'त्वम् सुखी अभवः।', 'Ты становился счастливым.'),
  (gen_random_uuid(), 'imperfectum', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām sukhinau abhavatam.', 'युवाम् सुखिनौ अभवतम्।', 'Вы вдвоем становились счастливыми.'),
  (gen_random_uuid(), 'imperfectum', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam sukhinaḥ abhavata.', 'यूयम् सुखिनः अभवत।', 'Вы становились счастливыми.'),
  (gen_random_uuid(), 'imperfectum', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 3, 'SINGULAR', 'Bālaḥ sukhī abhavat.', 'बालः सुखी अभवत्।', 'Мальчик становился счастливым.'),
  (gen_random_uuid(), 'imperfectum', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 3, 'DUAL', 'Bālau sukhinau abhavatām.', 'बालौ सुखिनौ अभवताम्।', 'Двое мальчиков становились счастливыми.'),
  (gen_random_uuid(), 'imperfectum', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 3, 'PLURAL', 'Bālāḥ sukhinaḥ abhavan.', 'बालाः सुखिनः अभवन्।', 'Мальчики становились счастливыми.'),
  (gen_random_uuid(), 'imperfectum', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ pustakaṁ apaṭham.', 'अहम् पुस्तकम् अपठम्।', 'Я читал книгу.'),
  (gen_random_uuid(), 'imperfectum', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 1, 'DUAL', 'Āvām pustakaṁ apaṭhāva.', 'आवाम् पुस्तकम् अपठाव।', 'Мы вдвоем читали книгу.'),
  (gen_random_uuid(), 'imperfectum', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam pustakaṁ apaṭhāma.', 'वयम् पुस्तकम् अपठाम।', 'Мы читали книгу.'),
  (gen_random_uuid(), 'imperfectum', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam pustakaṁ apaṭhaḥ.', 'त्वम् पुस्तकम् अपठः।', 'Ты читал книгу.'),
  (gen_random_uuid(), 'imperfectum', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām pustakaṁ apaṭhatam.', 'युवाम् पुस्तकम् अपठतम्।', 'Вы вдвоем читали книгу.'),
  (gen_random_uuid(), 'imperfectum', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam pustakaṁ apaṭhata.', 'यूयम् पुस्तकम् अपठत।', 'Вы читали книгу.'),
  (gen_random_uuid(), 'imperfectum', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 3, 'SINGULAR', 'Chātraḥ pustakaṁ apaṭhat.', 'छात्रः पुस्तकम् अपठत्।', 'Ученик читал книгу.'),
  (gen_random_uuid(), 'imperfectum', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 3, 'DUAL', 'Chātrau pustakaṁ apaṭhatām.', 'छात्रौ पुस्तकम् अपठताम्।', 'Двое учеников читали книгу.'),
  (gen_random_uuid(), 'imperfectum', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 3, 'PLURAL', 'Chātrāḥ pustakaṁ apaṭhan.', 'छात्राः पुस्तकम् अपठन्।', 'Ученики читали книгу.'),
  (gen_random_uuid(), 'imperfectum', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ gṛhaṁ agaccham.', 'अहम् गृहम् अगच्छम्।', 'Я шел домой.'),
  (gen_random_uuid(), 'imperfectum', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 1, 'DUAL', 'Āvām gṛhaṁ agacchāva.', 'आवाम् गृहम् अगच्छाव।', 'Мы вдвоем шли домой.'),
  (gen_random_uuid(), 'imperfectum', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam gṛhaṁ agacchāma.', 'वयम् गृहम् अगच्छाम।', 'Мы шли домой.'),
  (gen_random_uuid(), 'imperfectum', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam gṛhaṁ agacchaḥ.', 'त्वम् गृहम् अगच्छः।', 'Ты шел домой.'),
  (gen_random_uuid(), 'imperfectum', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām gṛhaṁ agacchatam.', 'युवाम् गृहम् अगच्छतम्।', 'Вы вдвоем шли домой.'),
  (gen_random_uuid(), 'imperfectum', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam gṛhaṁ agacchata.', 'यूयम् गृहम् अगच्छत।', 'Вы шли домой.'),
  (gen_random_uuid(), 'imperfectum', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 3, 'SINGULAR', 'Naraḥ gṛhaṁ agacchat.', 'नरः गृहम् अगच्छत्।', 'Человек шел домой.'),
  (gen_random_uuid(), 'imperfectum', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 3, 'DUAL', 'Narau gṛhaṁ agacchatām.', 'नरौ गृहम् अगच्छताम्।', 'Двое людей шли домой.'),
  (gen_random_uuid(), 'imperfectum', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 3, 'PLURAL', 'Narāḥ gṛhaṁ agacchan.', 'नराः गृहम् अगच्छन्।', 'Люди шли домой.'),
  (gen_random_uuid(), 'imperfectum', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ citraṁ apaśyam.', 'अहम् चित्रम् अपश्यम्।', 'Я видел картинку.'),
  (gen_random_uuid(), 'imperfectum', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 1, 'DUAL', 'Āvām citraṁ apaśyāva.', 'आवाम् चित्रम् अपश्याव।', 'Мы вдвоем видели картинку.'),
  (gen_random_uuid(), 'imperfectum', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam citraṁ apaśyāma.', 'वयम् चित्रम् अपश्याम।', 'Мы видели картинку.'),
  (gen_random_uuid(), 'imperfectum', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam citraṁ apaśyaḥ.', 'त्वम् चित्रम् अपश्यः।', 'Ты видел картинку.'),
  (gen_random_uuid(), 'imperfectum', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām citraṁ apaśyatam.', 'युवाम् चित्रम् अपश्यतम्।', 'Вы вдвоем видели картинку.'),
  (gen_random_uuid(), 'imperfectum', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam citraṁ apaśyata.', 'यूयम् चित्रम् अपश्यत।', 'Вы видели картинку.'),
  (gen_random_uuid(), 'imperfectum', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 3, 'SINGULAR', 'Bālaḥ citraṁ apaśyat.', 'बालः चित्रम् अपश्यत्।', 'Мальчик видел картинку.'),
  (gen_random_uuid(), 'imperfectum', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 3, 'DUAL', 'Bālau citraṁ apaśyatām.', 'बालौ चित्रम् अपश्यताम्।', 'Двое мальчиков видели картинку.'),
  (gen_random_uuid(), 'imperfectum', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 3, 'PLURAL', 'Bālāḥ citraṁ apaśyan.', 'बालाः चित्रम् अपश्यन्।', 'Мальчики видели картинку.'),
  (gen_random_uuid(), 'imperfectum', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ patraṁ alikham.', 'अहम् पत्रम् अलिखम्।', 'Я писал письмо.'),
  (gen_random_uuid(), 'imperfectum', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 1, 'DUAL', 'Āvām patraṁ alikhāva.', 'आवाम् पत्रम् अलिखाव।', 'Мы вдвоем писали письмо.'),
  (gen_random_uuid(), 'imperfectum', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam patraṁ alikhāma.', 'वयम् पत्रम् अलिखाम।', 'Мы писали письмо.'),
  (gen_random_uuid(), 'imperfectum', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam patraṁ alikhaḥ.', 'त्वम् पत्रम् अलिखः।', 'Ты писал письмо.'),
  (gen_random_uuid(), 'imperfectum', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām patraṁ alikhatam.', 'युवाम् पत्रम् अलिखतम्।', 'Вы вдвоем писали письмо.'),
  (gen_random_uuid(), 'imperfectum', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam patraṁ alikhata.', 'यूयम् पत्रम् अलिखत।', 'Вы писали письмо.'),
  (gen_random_uuid(), 'imperfectum', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 3, 'SINGULAR', 'Kaviḥ patraṁ alikhat.', 'कविः पत्रम् अलिखत्।', 'Поэт писал письмо.'),
  (gen_random_uuid(), 'imperfectum', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 3, 'DUAL', 'Kavī patraṁ alikhatām.', 'कवी पत्रम् अलिखताम्।', 'Двое поэтов писали письмо.'),
  (gen_random_uuid(), 'imperfectum', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 3, 'PLURAL', 'Kavayaḥ patraṁ alikhan.', 'कवयः पत्रम् अलिखन्।', 'Поэты писали письмо.'),
  (gen_random_uuid(), 'imperfectum', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ dhanaṁ alabhe.', 'अहम् धनम् अलभे।', 'Я получал богатство.'),
  (gen_random_uuid(), 'imperfectum', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 1, 'DUAL', 'Āvām dhanaṁ alabhāvahi.', 'आवाम् धनम् अलभावहि।', 'Мы вдвоем получали богатство.'),
  (gen_random_uuid(), 'imperfectum', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ dhanaṁ alabhāmahi.', 'वयम् धनम् अलभामहि।', 'Мы получали богатство.'),
  (gen_random_uuid(), 'imperfectum', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam dhanaṁ alabhathāḥ.', 'त्वम् धनम् अलथाः।', 'Ты получал богатство.'),
  (gen_random_uuid(), 'imperfectum', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 2, 'DUAL', 'Yuvām dhanaṁ alabhethām.', 'युवाम् धनम् अलभेथाम्।', 'Вы вдвоем получали богатство.'),
  (gen_random_uuid(), 'imperfectum', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam dhanaṁ alabhadhvam.', 'यूयम् धनम् अलमध्वम्।', 'Вы получали богатство.'),
  (gen_random_uuid(), 'imperfectum', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 3, 'SINGULAR', 'Naraḥ dhanaṁ alabhata.', 'नरः धनम् अलभत।', 'Человек получал богатство.'),
  (gen_random_uuid(), 'imperfectum', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 3, 'DUAL', 'Narau dhanaṁ alabhetām.', 'नरौ धनम् अलभेताम्।', 'Двое людей получали богатство.'),
  (gen_random_uuid(), 'imperfectum', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 3, 'PLURAL', 'Narāḥ dhanaṁ alabhanta.', 'नराः धनम् अलभन्त।', 'Люди получали богатство.'),
  (gen_random_uuid(), 'imperfectum', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ satyaṁ abhāṣe.', 'अहम् सत्यम् अभाषे।', 'Я говорил правду.'),
  (gen_random_uuid(), 'imperfectum', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 1, 'DUAL', 'Āvām satyaṁ abhāṣāvahi.', 'आवाम् सत्यम् अभाषावहि।', 'Мы вдвоем говорили правду.'),
  (gen_random_uuid(), 'imperfectum', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ satyaṁ abhāṣāmahi.', 'वयम् सत्यम् अभाषामहि।', 'Мы говорили правду.'),
  (gen_random_uuid(), 'imperfectum', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam satyaṁ abhāṣathāḥ.', 'त्वम् सत्यम् अभाषथाः।', 'Ты говорил правду.'),
  (gen_random_uuid(), 'imperfectum', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 2, 'DUAL', 'Yuvām satyaṁ abhāṣethām.', 'युवाम् सत्यम् अभाषेथाम्।', 'Вы вдвоем говорили правду.'),
  (gen_random_uuid(), 'imperfectum', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam satyaṁ abhāṣadhvam.', 'यूयम् सत्यम् अभाषध्वम्।', 'Вы говорили правду.'),
  (gen_random_uuid(), 'imperfectum', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 3, 'SINGULAR', 'Bālaḥ satyaṁ abhāṣata.', 'बालः सत्यम् अभाषत।', 'Мальчик говорил правду.'),
  (gen_random_uuid(), 'imperfectum', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 3, 'DUAL', 'Bālau satyaṁ abhāṣetām.', 'बालौ सत्यम् अभाषेताम्।', 'Двое мальчиков говорили правду.'),
  (gen_random_uuid(), 'imperfectum', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 3, 'PLURAL', 'Bālāḥ satyaṁ abhāṣanta.', 'बालाः सत्यम् अभाषन्त।', 'Мальчики говорили правду.'),
  (gen_random_uuid(), 'imperfectum', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ guruṁ aseve.', 'अहम् गुरुम् असेवे।', 'Я служил учителю.'),
  (gen_random_uuid(), 'imperfectum', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 1, 'DUAL', 'Āvām guruṁ asevāvahi.', 'आवाम् गुरुम् असेवावहि।', 'Мы вдвоем служили учителю.'),
  (gen_random_uuid(), 'imperfectum', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ guruṁ asevāmahi.', 'वयम् गुरुम् असेवामह।', 'Мы служили учителю.'),
  (gen_random_uuid(), 'imperfectum', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam guruṁ asevathāḥ.', 'त्वम् गुरुम् असेवथाः।', 'Ты служил учителю.'),
  (gen_random_uuid(), 'imperfectum', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 2, 'DUAL', 'Yuvām guruṁ asevethām.', 'युवाम् गुरुम् असेवेथाम्।', 'Вы вдвоем служили учителю.'),
  (gen_random_uuid(), 'imperfectum', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam guruṁ asevadhvam.', 'यूयम् गुरुम् असेवध्वम्।', 'Вы служили учителю.'),
  (gen_random_uuid(), 'imperfectum', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 3, 'SINGULAR', 'Chātraḥ guruṁ asevata.', 'छात्रः गुरुम् असेवत।', 'Ученик служил учителю.'),
  (gen_random_uuid(), 'imperfectum', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 3, 'DUAL', 'Chātrau guruṁ asevetām.', 'छात्रौ गुरुम् असेवेताम्।', 'Двое учеников служили учителю.'),
  (gen_random_uuid(), 'imperfectum', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 3, 'PLURAL', 'Chātrāḥ guruṁ asevanta.', 'छात्राः गुरुम् असेवन्त।', 'Ученики служили учителю.'),
  (gen_random_uuid(), 'imperfectum', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ atra avarte.', 'अहम् अत्र अवर्ते।', 'Я находился здесь.'),
  (gen_random_uuid(), 'imperfectum', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 1, 'DUAL', 'Āvām atra avartāvahi.', 'आवाम् अत्र अवर्तावहि।', 'Мы вдвоем находились здесь.'),
  (gen_random_uuid(), 'imperfectum', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ atra avartāmahi.', 'वयम् अत्र अवर्तामहि।', 'Мы находились здесь.'),
  (gen_random_uuid(), 'imperfectum', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam atra avartathāḥ.', 'त्वम् अत्र अवर्तथाः।', 'Ты находился здесь.'),
  (gen_random_uuid(), 'imperfectum', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 2, 'DUAL', 'Yuvām atra avartethām.', 'युवाम् अत्र अवर्तेथाम्।', 'Вы вдвоем находились здесь.'),
  (gen_random_uuid(), 'imperfectum', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam atra avartadhvam.', 'यूयम् अत्र अवर्तध्वम्।', 'Вы находились здесь.'),
  (gen_random_uuid(), 'imperfectum', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 3, 'SINGULAR', 'Śāntiḥ atra avartata.', 'शान्तिः अत्र अवर्तत।', 'Мир находился здесь.'),
  (gen_random_uuid(), 'imperfectum', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 3, 'DUAL', 'Śāntī atra avartetām.', 'शान्ती अत्र अवर्तेताम्।', 'Два состояния мира находились здесь.'),
  (gen_random_uuid(), 'imperfectum', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 3, 'PLURAL', 'Śāntayaḥ atra avartanta.', 'शान्तयः अत्र अवर्तन्त।', 'Состояния мира находились здесь.'),
  (gen_random_uuid(), 'imperfectum', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ sādhu amanye.', 'अहम् साधु अमन्ये।', 'Я считал это хорошим.'),
  (gen_random_uuid(), 'imperfectum', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 1, 'DUAL', 'Āvām sādhu amanyāvahi.', 'आवाम् साधु अमन्यावहि।', 'Мы вдвоем считали это хорошим.'),
  (gen_random_uuid(), 'imperfectum', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ sādhu amanyāmahi.', 'वयम् साधु अमन्यामहि।', 'Мы считали это хорошим.'),
  (gen_random_uuid(), 'imperfectum', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam sādhu amanyathāḥ.', 'त्वम् साधु अमन्यथाः।', 'Ты считал это хорошим.'),
  (gen_random_uuid(), 'imperfectum', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 2, 'DUAL', 'Yuvām sādhu amanyethām.', 'युवाम् साधु अमन्येथाम्।', 'Вы вдвоем считали это хорошим.'),
  (gen_random_uuid(), 'imperfectum', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam sādhu amanyadhvam.', 'यूयम् साधु अमन्यध्वम्।', 'Вы считали это хорошим.'),
  (gen_random_uuid(), 'imperfectum', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 3, 'SINGULAR', 'Nṛpaḥ sādhu amanyata.', 'नृपः साधु अमन्यत।', 'Царь считал это хорошим.'),
  (gen_random_uuid(), 'imperfectum', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 3, 'DUAL', 'Nṛpau sādhu amanyetām.', 'नृपौ साधु अमन्येताम्।', 'Двое царей считали это хорошим.'),
  (gen_random_uuid(), 'imperfectum', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 3, 'PLURAL', 'Nṛpāḥ sādhu amanyanta.', 'नृपाः साधु अमन्यन्त।', 'Цари считали это хорошим.');
