-- V37: conjugation paradigms for the optativus lesson.
-- Optative example sentences (person x number = 9 per verb) for the verb lesson
-- optativus. Source: etcetera/grammar/sanskrit_verbs_optative.json.
-- Served by ConjugationParadigmService as an index-based carousel (one verb per page).

INSERT INTO curriculum.conjugation_forms
    (id, topic_code, lemma_iast, lemma_devanagari, meaning_ru, voice, person, number_type, sentence_iast, sentence_devanagari, translation_ru)
VALUES
  (gen_random_uuid(), 'optativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ sukhī bhaveyam.', 'अहम् सुखी भवेयम्।', 'Пусть я буду счастливым (хотел бы я быть счастливым).'),
  (gen_random_uuid(), 'optativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 1, 'DUAL', 'Āvām sukhinau bhaveva.', 'आवाम् सुखिनौ भवेव।', 'Пусть мы вдвоем будем счастливыми.'),
  (gen_random_uuid(), 'optativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam sukhinaḥ bhavema.', 'वयम् सुखिनः भवेम।', 'Пусть мы будем счастливыми.'),
  (gen_random_uuid(), 'optativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam sukhī bhaveḥ.', 'त्वम् सुखी भवेः।', 'Тебе следует быть счастливым.'),
  (gen_random_uuid(), 'optativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām sukhinau bhavetam.', 'युवाम् सुखिनौ भवेतम्।', 'Вам вдвоем следует быть счастливыми.'),
  (gen_random_uuid(), 'optativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam sukhinaḥ bhaveta.', 'यूयम् सुखिनः भवेत।', 'Вам следует быть счастливыми.'),
  (gen_random_uuid(), 'optativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 3, 'SINGULAR', 'Bālaḥ sukhī bhavet.', 'बालः सुखी भवेत्।', 'Пусть мальчик будет счастливым.'),
  (gen_random_uuid(), 'optativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 3, 'DUAL', 'Bālau sukhinau bhavetām.', 'बालौ सुखिनौ भवेताम्।', 'Пусть двое мальчиков будут счастливыми.'),
  (gen_random_uuid(), 'optativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 3, 'PLURAL', 'Bālāḥ sukhinaḥ bhaveyuḥ.', 'बालाः सुखिनः भवेयुः।', 'Пусть мальчики будут счастливыми.'),
  (gen_random_uuid(), 'optativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ pustakaṁ paṭheyam.', 'अहम् पुस्तकम् पठेयम्।', 'Мне следует читать книгу.'),
  (gen_random_uuid(), 'optativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 1, 'DUAL', 'Āvām pustakaṁ paṭheva.', 'आवाम् पुस्तकम् पठेव।', 'Нам вдвоем следует читать книгу.'),
  (gen_random_uuid(), 'optativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam pustakaṁ paṭhema.', 'वयम् पुस्तकम् पठेम।', 'Нам следует читать книгу.'),
  (gen_random_uuid(), 'optativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam pustakaṁ paṭheḥ.', 'त्वम् पुस्तकम् पठेः।', 'Тебе следует читать книгу.'),
  (gen_random_uuid(), 'optativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām pustakaṁ paṭhetam.', 'युवाम् पुस्तकम् पठेत्।', 'Вам вдвоем следует читать книгу.'),
  (gen_random_uuid(), 'optativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam pustakaṁ paṭheta.', 'यूयम् पुस्तकम् पठेत्।', 'Вам следует читать книгу.'),
  (gen_random_uuid(), 'optativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 3, 'SINGULAR', 'Chātraḥ pustakaṁ paṭhet.', 'छात्रः पुस्तकम् पठेत्।', 'Пусть ученик читает книгу.'),
  (gen_random_uuid(), 'optativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 3, 'DUAL', 'Chātrau pustakaṁ paṭhetām.', 'छात्रौ पुस्तकम् पठेताम्।', 'Пусть двое учеников читают книгу.'),
  (gen_random_uuid(), 'optativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 3, 'PLURAL', 'Chātrāḥ pustakaṁ paṭheyuh.', 'छात्राः पुस्तकम् पठेयुः।', 'Пусть ученики читают книгу.'),
  (gen_random_uuid(), 'optativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ gṛhaṁ gaccheyam.', 'अहम् गृहम् गच्छेयम्।', 'Я хотел бы пойти домой.'),
  (gen_random_uuid(), 'optativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 1, 'DUAL', 'Āvām gṛhaṁ gaccheva.', 'आवाम् गृहम् गच्छेव।', 'Мы вдвоем хотели бы пойти домой.'),
  (gen_random_uuid(), 'optativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam gṛhaṁ gacchema.', 'वयम् गृहम् गच्छेम।', 'Мы хотели бы пойти домой.'),
  (gen_random_uuid(), 'optativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam gṛhaṁ gaccheḥ.', 'त्वम् गृहम् गच्छेः।', 'Тебе следует пойти домой.'),
  (gen_random_uuid(), 'optativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām gṛhaṁ gacchetam.', 'युवाम् गृहम् गच्छेतम्।', 'Вам вдвоем следует пойти домой.'),
  (gen_random_uuid(), 'optativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam gṛhaṁ gaccheta.', 'यूयम् गृहम् गच्छेत।', 'Вам следует пойти домой.'),
  (gen_random_uuid(), 'optativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 3, 'SINGULAR', 'Naraḥ gṛhaṁ gacchet.', 'नरः गृहम् गच्छेत्।', 'Пусть человек пойдет домой.'),
  (gen_random_uuid(), 'optativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 3, 'DUAL', 'Narau gṛhaṁ gacchetām.', 'नरौ गृहम् गच्छेताम्।', 'Пусть двое людей пойдут домой.'),
  (gen_random_uuid(), 'optativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 3, 'PLURAL', 'Narāḥ gṛhaṁ gaccheyuḥ.', 'नराः गृहम् गच्छेयुः।', 'Пусть люди пойдут домой.'),
  (gen_random_uuid(), 'optativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ citraṁ paśyeyam.', 'अहम् चित्रम् पश्येयम्।', 'Я хотел бы посмотреть картину.'),
  (gen_random_uuid(), 'optativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 1, 'DUAL', 'Āvām citraṁ paśyeva.', 'आवाम् चित्रम् पश्येव।', 'Мы вдвоем хотели бы посмотреть картину.'),
  (gen_random_uuid(), 'optativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam citraṁ paśyema.', 'वयम् चित्रम् पश्येम।', 'Мы хотели бы посмотреть картину.'),
  (gen_random_uuid(), 'optativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam citraṁ paśyeḥ.', 'त्वम् चित्रम् पश्येः।', 'Тебе следует посмотреть картину.'),
  (gen_random_uuid(), 'optativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām citraṁ paśyetam.', 'युवाम् चित्रम् पश्येतम्।', 'Вам вдвоем следует посмотреть картину.'),
  (gen_random_uuid(), 'optativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam citraṁ paśyeta.', 'यूयम् चित्रम् पश्येत।', 'Вам следует посмотреть картину.'),
  (gen_random_uuid(), 'optativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 3, 'SINGULAR', 'Bālaḥ citraṁ paśyet.', 'बालः चित्रम् पश्येत्।', 'Пусть мальчик посмотрит картину.'),
  (gen_random_uuid(), 'optativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 3, 'DUAL', 'Bālau citraṁ paśyetām.', 'बालौ चित्रम् पश्येताम्।', 'Пусть двое мальчиков смотрят картину.'),
  (gen_random_uuid(), 'optativus', 'dṛś', 'दृश्', 'видеть', 'PARASMAIPADA', 3, 'PLURAL', 'Bālāḥ citraṁ paśyeyuḥ.', 'बालाः चित्रम् पश्येयुः।', 'Пусть мальчики смотрят картину.'),
  (gen_random_uuid(), 'optativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ patraṁ likheyam.', 'अहम् पत्रम् लिखेयम्।', 'Я хотел бы написать письмо.'),
  (gen_random_uuid(), 'optativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 1, 'DUAL', 'Āvām patraṁ likheva.', 'आवाम् पत्रम् लिखेव।', 'Мы вдвоем хотели бы написать письмо.'),
  (gen_random_uuid(), 'optativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam patraṁ likhema.', 'वयम् पत्रम् लिखेम।', 'Мы хотели бы написать письмо.'),
  (gen_random_uuid(), 'optativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam patraṁ likheḥ.', 'त्वम् पत्रम् लिखेः।', 'Тебе следует написать письмо.'),
  (gen_random_uuid(), 'optativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām patraṁ likhetam.', 'युवाम् पत्रम् लिखेत्।', 'Вам вдвоем следует написать письмо.'),
  (gen_random_uuid(), 'optativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam patraṁ likheta.', 'यूयम् पत्रम् लिखेत्।', 'Вам следует написать письмо.'),
  (gen_random_uuid(), 'optativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 3, 'SINGULAR', 'Kaviḥ patraṁ likhet.', 'कविः पत्रम् लिखेत्।', 'Пусть поэт напишет письмо.'),
  (gen_random_uuid(), 'optativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 3, 'DUAL', 'Kavī patraṁ likhetām.', 'कवी पत्रम् लिखेताम्।', 'Пусть двое поэтов напишут письмо.'),
  (gen_random_uuid(), 'optativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 3, 'PLURAL', 'Kavayaḥ patraṁ likheyuḥ.', 'कवयः पत्रम् लिखेयुः।', 'Пусть поэты напишут письмо.'),
  (gen_random_uuid(), 'optativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ dhanaṁ labheya.', 'अहम् धनम् लभेय।', 'Пусть я получу богатство.'),
  (gen_random_uuid(), 'optativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 1, 'DUAL', 'Āvām dhanaṁ labhevahi.', 'आवाम् धनम् लभेवहि।', 'Пусть мы вдвоем получим богатство.'),
  (gen_random_uuid(), 'optativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ dhanaṁ labhemahi.', 'वयम् धनम् लभेमहि।', 'Пусть мы получим богатство.'),
  (gen_random_uuid(), 'optativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam dhanaṁ labhethāḥ.', 'त्वम् धनम् लभेथाः।', 'Тебе следует получить богатство.'),
  (gen_random_uuid(), 'optativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 2, 'DUAL', 'Yuvām dhanaṁ labheyāthām.', 'युवाम् धनम् लभेयाथाम्।', 'Вам вдвоем следует получить богатство.'),
  (gen_random_uuid(), 'optativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam dhanaṁ labhedhvam.', 'यूयम् धनम् लभेध्वम्।', 'Вам следует получить богатство.'),
  (gen_random_uuid(), 'optativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 3, 'SINGULAR', 'Naraḥ dhanaṁ labheta.', 'नरः धनम् लभेत।', 'Пусть человек получит богатство.'),
  (gen_random_uuid(), 'optativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 3, 'DUAL', 'Narau dhanaṁ labheyātām.', 'नरौ धनम् लभेयाताम्।', 'Пусть двое людей получат богатство.'),
  (gen_random_uuid(), 'optativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 3, 'PLURAL', 'Narāḥ dhanaṁ labheran.', 'नराः धनम् लभेरन्।', 'Пусть люди получат богатство.'),
  (gen_random_uuid(), 'optativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ satyaṁ bhāṣeya.', 'अहम् सत्यम् भाषेय।', 'Мне следует говорить правду.'),
  (gen_random_uuid(), 'optativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 1, 'DUAL', 'Āvām satyaṁ bhāṣevahi.', 'आवाम् सत्यम् भाषेवहि।', 'Нам вдвоем следует говорить правду.'),
  (gen_random_uuid(), 'optativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ satyaṁ bhāṣemahi.', 'वयम् सत्यम् भाषेमहि।', 'Нам следует говорить правду.'),
  (gen_random_uuid(), 'optativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam satyaṁ bhāṣethāḥ.', 'त्वम् सत्यम् भाषेथाः।', 'Тебе следует говорить правду.'),
  (gen_random_uuid(), 'optativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 2, 'DUAL', 'Yuvām satyaṁ bhāṣeyāthām.', 'युवाम् सत्यम् भाषेयाथाम्।', 'Вам вдвоем следует говорить правду.'),
  (gen_random_uuid(), 'optativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam satyaṁ bhāṣedhvam.', 'यूयम् सत्यम् भाषेध्वम्।', 'Вам следует говорить правду.'),
  (gen_random_uuid(), 'optativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 3, 'SINGULAR', 'Bālaḥ satyaṁ bhāṣeta.', 'बालः सत्यम् भाषेत।', 'Пусть мальчик говорит правду.'),
  (gen_random_uuid(), 'optativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 3, 'DUAL', 'Bālau satyaṁ bhāṣeyātām.', 'बालौ सत्यम् भाषेयाताम्।', 'Пусть двое мальчиков говорят правду.'),
  (gen_random_uuid(), 'optativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 3, 'PLURAL', 'Bālāḥ satyaṁ bhāṣeran.', 'बालाः सत्यम् भाषेन्।', 'Пусть мальчики говорят правду.'),
  (gen_random_uuid(), 'optativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ guruṁ seveya.', 'अहम् गुरुम् सेवेय।', 'Мне следует служить учителю.'),
  (gen_random_uuid(), 'optativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 1, 'DUAL', 'Āvām guruṁ sevevahi.', 'आवाम् गुरुम् सेवेवहि।', 'Нам вдвоем следует служить учителю.'),
  (gen_random_uuid(), 'optativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ guruṁ sevemahi.', 'वयम् गुरुम् सेवेमहि।', 'Нам следует служить учителю.'),
  (gen_random_uuid(), 'optativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam guruṁ sevethāḥ.', 'त्वम् गुरुम् सेवेथाः।', 'Тебе следует служить учителю.'),
  (gen_random_uuid(), 'optativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 2, 'DUAL', 'Yuvām guruṁ seveyāthām.', 'युवाम् गुरुम् सेवेयाथाम्।', 'Вам вдвоем следует служить учителю.'),
  (gen_random_uuid(), 'optativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam guruṁ sevedhvam.', 'यूयम् गुरुम् सेवेध्वम्।', 'Вам следует служить учителю.'),
  (gen_random_uuid(), 'optativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 3, 'SINGULAR', 'Chātraḥ guruṁ seveta.', 'छात्रः गुरुम् सेवेत।', 'Пусть ученик служит учителю.'),
  (gen_random_uuid(), 'optativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 3, 'DUAL', 'Chātrau guruṁ seveyātām.', 'छात्रौ गुरुम् सेवेयाताम्।', 'Пусть двое учеников служат учителю.'),
  (gen_random_uuid(), 'optativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 3, 'PLURAL', 'Chātrāḥ guruṁ severan.', 'छात्राः गुरुम् सेवेरन्।', 'Пусть ученики служат учителю.'),
  (gen_random_uuid(), 'optativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ atra varteya.', 'अहम् अत्र वर्तेय।', 'Я хотел бы находиться здесь.'),
  (gen_random_uuid(), 'optativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 1, 'DUAL', 'Āvām atra vartevahi.', 'आवाम् अत्र वर्तेवहि।', 'Мы вдвоем хотели бы находиться здесь.'),
  (gen_random_uuid(), 'optativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ atra vartemahi.', 'वयम् अत्र वर्तेमहि।', 'Мы хотели бы находиться здесь.'),
  (gen_random_uuid(), 'optativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam atra vartethāḥ.', 'त्वम् अत्र वर्तेथाः।', 'Тебе следует находиться здесь.'),
  (gen_random_uuid(), 'optativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 2, 'DUAL', 'Yuvām atra varteyāthām.', 'युवाम् अत्र वर्तेयाथाम्।', 'Вам вдвоем следует находиться здесь.'),
  (gen_random_uuid(), 'optativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam atra vartedhvam.', 'यूयम् अत्र वर्तेध्वम्।', 'Вам следует находиться здесь.'),
  (gen_random_uuid(), 'optativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 3, 'SINGULAR', 'Śāntiḥ atra varteta.', 'शान्तिः अत्र वर्तेत।', 'Пусть мир пребывает здесь.'),
  (gen_random_uuid(), 'optativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 3, 'DUAL', 'Śāntī atra varteyātām.', 'शान्ती अत्र वर्तेयाताम्।', 'Пусть две формы мира пребывают здесь.'),
  (gen_random_uuid(), 'optativus', 'vṛt', 'वृत्', 'находиться, существовать', 'ATMANEPADA', 3, 'PLURAL', 'Śāntayaḥ atra varteran.', 'शान्तयः अत्र वर्तेरन्।', 'Пусть мир во всех проявлениях пребывает здесь.'),
  (gen_random_uuid(), 'optativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ sādhu manyeya.', 'अहम् साधु मन्येय।', 'Я хотел бы считать это правильным.'),
  (gen_random_uuid(), 'optativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 1, 'DUAL', 'Āvām sādhu manyevahi.', 'आवाम् साधु मन्येवहि।', 'Мы вдвоем хотели бы считать это правильным.'),
  (gen_random_uuid(), 'optativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 1, 'PLURAL', 'Vayaṁ sādhu manyemahi.', 'वयम् साधु मन्येमहि।', 'Мы хотели бы считать это правильным.'),
  (gen_random_uuid(), 'optativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam sādhu manyethāḥ.', 'त्वम् साधु मन्येथाः।', 'Тебе следует считать это правильным.'),
  (gen_random_uuid(), 'optativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 2, 'DUAL', 'Yuvām sādhu manyeyāthām.', 'युवाम् साधु मन्येयाथाम्।', 'Вам вдвоем следует считать это правильным.'),
  (gen_random_uuid(), 'optativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam sādhu manyedhvam.', 'यूयम् साधु मन्येध्वम्।', 'Вам следует считать это правильным.'),
  (gen_random_uuid(), 'optativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 3, 'SINGULAR', 'Nṛpaḥ sādhu manyeta.', 'नृपः साधु मन्येत।', 'Пусть царь считает это правильным.'),
  (gen_random_uuid(), 'optativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 3, 'DUAL', 'Nṛpau sādhu manyeyātām.', 'नृपौ साधु मन्येयाताम्।', 'Пусть двое царей считают это правильным.'),
  (gen_random_uuid(), 'optativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 3, 'PLURAL', 'Nṛpāḥ sādhu manyeran.', 'नृपाः साधु मन्येन्न।', 'Пусть цари считают это правильным.');
