-- V38: imperative (Imperativus) conjugation lesson: rename + seed paradigms.
--
-- The imperative topic (code 'imperative', L4) is renamed to the Latin-namespace
-- 'imperativus' and releveled to L2, mirroring the V34 renaming of the other
-- verb lessons. Prerequisite edges and quest bindings reference topic_id (UUID),
-- not code, so renaming the code does not break them. display_order is appended
-- to the end of the target learning level (tie-break within a level, curriculum.md §2).
--
-- Then conjugation paradigms (person x number = 9 per verb, 10 verbs) are seeded
-- for the imperativus lesson. Source: etcetera/grammar/sanskrit_verbs_imperative.json.
-- Served by ConjugationParadigmService as an index-based carousel (one verb per page).

UPDATE curriculum.topic
SET code = 'imperativus',
    title_ru = 'Повелительное наклонение',
    title_en = 'Imperative mood',
    learning_level = 'L2',
    display_order = (SELECT COALESCE(MAX(display_order), 0) + 1
                     FROM curriculum.topic WHERE learning_level = 'L2')
WHERE code = 'imperative';

INSERT INTO curriculum.conjugation_forms
    (id, topic_code, lemma_iast, lemma_devanagari, meaning_ru, voice, person, number_type, sentence_iast, sentence_devanagari, translation_ru)
VALUES
  (gen_random_uuid(), 'imperativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ bhavāni.', 'अहम् भवानि।', 'Да буду я! (Дай мне стать).'),
  (gen_random_uuid(), 'imperativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 1, 'DUAL', 'Āvām bhavāva.', 'आवाम् भवाव।', 'Да будем мы вдвоем!'),
  (gen_random_uuid(), 'imperativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam bhavāma.', 'वयम् भवाम।', 'Да будем мы!'),
  (gen_random_uuid(), 'imperativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam bhava.', 'त्वम् भव।', 'Будь!'),
  (gen_random_uuid(), 'imperativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām bhavatam.', 'युवाम् भवतम्।', 'Будьте вдвоем!'),
  (gen_random_uuid(), 'imperativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam bhavata.', 'यूयम् भवत।', 'Будьте!'),
  (gen_random_uuid(), 'imperativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 3, 'SINGULAR', 'Saḥ bhavatu.', 'सः भवतु।', 'Пусть он будет!'),
  (gen_random_uuid(), 'imperativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 3, 'DUAL', 'Tau bhavatām.', 'तौ भवताम्।', 'Пусть они вдвоем будут!'),
  (gen_random_uuid(), 'imperativus', 'bhū', 'भू', 'быть, становиться', 'PARASMAIPADA', 3, 'PLURAL', 'Te bhavantu.', 'ते भवन्तु।', 'Пусть они будут!'),
  (gen_random_uuid(), 'imperativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ paṭhāni.', 'अहम् पठानि।', 'Дай-ка я почитаю.'),
  (gen_random_uuid(), 'imperativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 1, 'DUAL', 'Āvām paṭhāva.', 'आवाम् पठाव।', 'Давай почитаем вдвоем.'),
  (gen_random_uuid(), 'imperativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam paṭhāma.', 'वयम् पठाम।', 'Давайте почитаем.'),
  (gen_random_uuid(), 'imperativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam paṭha.', 'त्वम् पठ।', 'Читай!'),
  (gen_random_uuid(), 'imperativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām paṭhatam.', 'युवाम् पठतम्।', 'Читайте вдвоем!'),
  (gen_random_uuid(), 'imperativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam paṭhata.', 'यूयम् पठत।', 'Читайте!'),
  (gen_random_uuid(), 'imperativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 3, 'SINGULAR', 'Chātraḥ paṭhatu.', 'छात्रः पठतु।', 'Пусть ученик читает.'),
  (gen_random_uuid(), 'imperativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 3, 'DUAL', 'Chātrau paṭhatām.', 'छात्रौ पठताम्।', 'Пусть двое учеников читают.'),
  (gen_random_uuid(), 'imperativus', 'paṭh', 'पठ्', 'читать', 'PARASMAIPADA', 3, 'PLURAL', 'Chātrāḥ paṭhantu.', 'छात्राः पठन्तु।', 'Пусть ученики читают.'),
  (gen_random_uuid(), 'imperativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ gacchāni.', 'अहम् गच्छानि।', 'Дай я пойду.'),
  (gen_random_uuid(), 'imperativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 1, 'DUAL', 'Āvām gacchāva.', 'आवाम् गच्छाव।', 'Пойдем вдвоем.'),
  (gen_random_uuid(), 'imperativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam gacchāma.', 'वयम् गच्छाम।', 'Пойдемте.'),
  (gen_random_uuid(), 'imperativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam gaccha.', 'त्वम् गच्छ।', 'Иди!'),
  (gen_random_uuid(), 'imperativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām gacchatam.', 'युवाम् गच्छतम्।', 'Идите вдвоем!'),
  (gen_random_uuid(), 'imperativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam gacchata.', 'यूयम् गच्छत।', 'Идите!'),
  (gen_random_uuid(), 'imperativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 3, 'SINGULAR', 'Bālaḥ gacchatu.', 'बालः गच्छतु।', 'Пусть мальчик идет.'),
  (gen_random_uuid(), 'imperativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 3, 'DUAL', 'Bālau gacchatām.', 'बालौ गच्छताम्।', 'Пусть двое мальчиков идут.'),
  (gen_random_uuid(), 'imperativus', 'gam', 'गम्', 'идти', 'PARASMAIPADA', 3, 'PLURAL', 'Bālāḥ gacchantu.', 'बालाः गच्छन्तु।', 'Пусть мальчики идут.'),
  (gen_random_uuid(), 'imperativus', 'dṛś', 'दृश्', 'видеть, смотреть', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ paśyāni.', 'अहम् पश्यानि।', 'Дай-ка я посмотрю.'),
  (gen_random_uuid(), 'imperativus', 'dṛś', 'दृश्', 'видеть, смотреть', 'PARASMAIPADA', 1, 'DUAL', 'Āvām paśyāva.', 'आवाम् पश्याव।', 'Давай посмотрим вдвоем.'),
  (gen_random_uuid(), 'imperativus', 'dṛś', 'दृश्', 'видеть, смотреть', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam paśyāma.', 'वयम् पश्याम।', 'Давайте посмотрим.'),
  (gen_random_uuid(), 'imperativus', 'dṛś', 'दृश्', 'видеть, смотреть', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam paśya.', 'त्वम् पश्य।', 'Смотри!'),
  (gen_random_uuid(), 'imperativus', 'dṛś', 'दृश्', 'видеть, смотреть', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām paśyatam.', 'युवाम् पश्यतम्।', 'Смотрите вдвоем!'),
  (gen_random_uuid(), 'imperativus', 'dṛś', 'दृश्', 'видеть, смотреть', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam paśyata.', 'यूयम् पश्यत।', 'Смотрите!'),
  (gen_random_uuid(), 'imperativus', 'dṛś', 'दृश्', 'видеть, смотреть', 'PARASMAIPADA', 3, 'SINGULAR', 'Janaḥ paśyatu.', 'जनः पश्यतु।', 'Пусть человек смотрит.'),
  (gen_random_uuid(), 'imperativus', 'dṛś', 'दृश्', 'видеть, смотреть', 'PARASMAIPADA', 3, 'DUAL', 'Janau paśyatām.', 'जनौ पश्यताम्।', 'Пусть двое людей смотрят.'),
  (gen_random_uuid(), 'imperativus', 'dṛś', 'दृश्', 'видеть, смотреть', 'PARASMAIPADA', 3, 'PLURAL', 'Janāḥ paśyantu.', 'जनाः पश्यन्तु।', 'Пусть люди смотрят.'),
  (gen_random_uuid(), 'imperativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 1, 'SINGULAR', 'Ahaṁ likhāni.', 'अहम् लिखानि।', 'Дай-ка я напишу.'),
  (gen_random_uuid(), 'imperativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 1, 'DUAL', 'Āvām likhāva.', 'आवाम् लिखाव।', 'Давай напишем вдвоем.'),
  (gen_random_uuid(), 'imperativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 1, 'PLURAL', 'Vayam likhāma.', 'वयम् लिखाम।', 'Давайте напишем.'),
  (gen_random_uuid(), 'imperativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 2, 'SINGULAR', 'Tvam likha.', 'त्वम् लिख।', 'Пиши!'),
  (gen_random_uuid(), 'imperativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 2, 'DUAL', 'Yuvām likhatam.', 'युवाम् लिखतम्।', 'Пишите вдвоем!'),
  (gen_random_uuid(), 'imperativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 2, 'PLURAL', 'Yūyam likhata.', 'यूयम् लिखत।', 'Пишите!'),
  (gen_random_uuid(), 'imperativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 3, 'SINGULAR', 'Bālikā likhatu.', 'बालिका लिखतु।', 'Пусть девочка пишет.'),
  (gen_random_uuid(), 'imperativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 3, 'DUAL', 'Bālike likhatām.', 'बालिके लिखताम्।', 'Пусть две девочки пишут.'),
  (gen_random_uuid(), 'imperativus', 'likh', 'लिख्', 'писать', 'PARASMAIPADA', 3, 'PLURAL', 'Bālikāḥ likhantu.', 'बालिकाः लिखन्तु।', 'Пусть девочки пишут.'),
  (gen_random_uuid(), 'imperativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ labhai.', 'अहम् लभै।', 'Дай-ка я получу.'),
  (gen_random_uuid(), 'imperativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 1, 'DUAL', 'Āvām labhāvahai.', 'आवाम् लभावहै।', 'Давай получим вдвоем.'),
  (gen_random_uuid(), 'imperativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 1, 'PLURAL', 'Vayam labhāmahai.', 'वयम् लभामहै।', 'Давайте получим.'),
  (gen_random_uuid(), 'imperativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam labhasva.', 'त्वम् लभस्व।', 'Получай!'),
  (gen_random_uuid(), 'imperativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 2, 'DUAL', 'Yuvām labhethām.', 'युवाम् लभेथाम्।', 'Получайте вдвоем!'),
  (gen_random_uuid(), 'imperativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam labhadhvam.', 'यूयम् लभध्वम्।', 'Получайте!'),
  (gen_random_uuid(), 'imperativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 3, 'SINGULAR', 'Saḥ labhatām.', 'सः लभताम्।', 'Пусть он получит.'),
  (gen_random_uuid(), 'imperativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 3, 'DUAL', 'Tau labhetām.', 'तौ लभेताम्।', 'Пусть они вдвоем получат.'),
  (gen_random_uuid(), 'imperativus', 'labh', 'लभ्', 'получать', 'ATMANEPADA', 3, 'PLURAL', 'Te labhantām.', 'ते लभन्ताम्।', 'Пусть они получат.'),
  (gen_random_uuid(), 'imperativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ bhāṣai.', 'अहम् भाषै।', 'Дай-ка я скажу.'),
  (gen_random_uuid(), 'imperativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 1, 'DUAL', 'Āvām bhāṣāvahai.', 'आवाम् भाषावहै।', 'Давай поговорим вдвоем.'),
  (gen_random_uuid(), 'imperativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 1, 'PLURAL', 'Vayam bhāṣāmahai.', 'वयम् भाषामहै।', 'Давайте поговорим.'),
  (gen_random_uuid(), 'imperativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam bhāṣasva.', 'त्वम् भाषस्व।', 'Говори!'),
  (gen_random_uuid(), 'imperativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 2, 'DUAL', 'Yuvām bhāṣethām.', 'युवाम् भाषेथाम्।', 'Говорите вдвоем!'),
  (gen_random_uuid(), 'imperativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam bhāṣadhvam.', 'यूयम् भाषध्वम्।', 'Говорите!'),
  (gen_random_uuid(), 'imperativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 3, 'SINGULAR', 'Vaktā bhāṣatām.', 'वक्ता भाषताम्।', 'Пусть оратор говорит.'),
  (gen_random_uuid(), 'imperativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 3, 'DUAL', 'Vaktārau bhāṣetām.', 'वक्तारौ भाषेताम्।', 'Пусть двое ораторов говорят.'),
  (gen_random_uuid(), 'imperativus', 'bhāṣ', 'भाष्', 'говорить', 'ATMANEPADA', 3, 'PLURAL', 'Vaktāraḥ bhāṣantām.', 'वक्तारः भाषन्ताम्।', 'Пусть ораторы говорят.'),
  (gen_random_uuid(), 'imperativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ sevai.', 'अहम् सेवै।', 'Дай-ка я послужу.'),
  (gen_random_uuid(), 'imperativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 1, 'DUAL', 'Āvām sevāvahai.', 'आवाम् सेवावहै।', 'Давай послужим вдвоем.'),
  (gen_random_uuid(), 'imperativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 1, 'PLURAL', 'Vayam sevāmahai.', 'वयम् सेवामहै।', 'Давайте послужим.'),
  (gen_random_uuid(), 'imperativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam sevasva.', 'त्वम् सेवस्व।', 'Служи!'),
  (gen_random_uuid(), 'imperativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 2, 'DUAL', 'Yuvām sevethām.', 'युवाम् सेवेथाम्।', 'Служите вдвоем!'),
  (gen_random_uuid(), 'imperativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam sevadhvam.', 'यूयम् सेवध्वम्।', 'Служите!'),
  (gen_random_uuid(), 'imperativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 3, 'SINGULAR', 'Bhaktaḥ mevatām.', 'भक्तः सेवताम्।', 'Пусть преданный служит.'),
  (gen_random_uuid(), 'imperativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 3, 'DUAL', 'Bhaktu sevethām.', 'भक्तौ सेवेताम्।', 'Пусть двое преданных служат.'),
  (gen_random_uuid(), 'imperativus', 'sev', 'सेव्', 'служить', 'ATMANEPADA', 3, 'PLURAL', 'Bhaktāḥ mevantām.', 'भक्ताः सेवन्ताम्।', 'Пусть преданные служат.'),
  (gen_random_uuid(), 'imperativus', 'vṛt', 'वृत्', 'находиться, действовать', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ vartai.', 'अहम् वर्तै।', 'Дай-ка я побуду / начну действовать.'),
  (gen_random_uuid(), 'imperativus', 'vṛt', 'वृत्', 'находиться, действовать', 'ATMANEPADA', 1, 'DUAL', 'Āvām vartāvahai.', 'आवाम् वर्तावहै।', 'Давай побудем вдвоем.'),
  (gen_random_uuid(), 'imperativus', 'vṛt', 'वृत्', 'находиться, действовать', 'ATMANEPADA', 1, 'PLURAL', 'Vayam vartāmahai.', 'वयम् वर्तामहै।', 'Давайте побудем.'),
  (gen_random_uuid(), 'imperativus', 'vṛt', 'वृत्', 'находиться, действовать', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam vartasva.', 'त्वम् वर्तस्व।', 'Будь! Действуй!'),
  (gen_random_uuid(), 'imperativus', 'vṛt', 'वृत्', 'находиться, действовать', 'ATMANEPADA', 2, 'DUAL', 'Yuvām vartethām.', 'युवाम् वर्तेथाम्।', 'Будьте / действуйте вдвоем!'),
  (gen_random_uuid(), 'imperativus', 'vṛt', 'वृत्', 'находиться, действовать', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam vartadhvam.', 'यूयम् वर्तध्वम्।', 'Будьте! Действуйте!'),
  (gen_random_uuid(), 'imperativus', 'vṛt', 'वृत्', 'находиться, действовать', 'ATMANEPADA', 3, 'SINGULAR', 'Saḥ vartatām.', 'सः वर्तताम्।', 'Пусть он пребывает.'),
  (gen_random_uuid(), 'imperativus', 'vṛt', 'वृत्', 'находиться, действовать', 'ATMANEPADA', 3, 'DUAL', 'Tau vartetām.', 'तौ वर्तेताम्।', 'Пусть они вдвоем пребывают.'),
  (gen_random_uuid(), 'imperativus', 'vṛt', 'वृत्', 'находиться, действовать', 'ATMANEPADA', 3, 'PLURAL', 'Te vartantām.', 'ते वर्तन्ताम्।', 'Пусть они пребывают.'),
  (gen_random_uuid(), 'imperativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 1, 'SINGULAR', 'Ahaṁ manyai.', 'अहम् मन्यै।', 'Дай-ка я подумаю.'),
  (gen_random_uuid(), 'imperativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 1, 'DUAL', 'Āvām manyāvahai.', 'आवाम् मन्यावहै।', 'Давай подумаем вдвоем.'),
  (gen_random_uuid(), 'imperativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 1, 'PLURAL', 'Vayam manyāmahai.', 'वयम् मन्यामहै।', 'Давайте подумаем.'),
  (gen_random_uuid(), 'imperativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 2, 'SINGULAR', 'Tvam manyasva.', 'त्वम् मन्यस्व।', 'Думай! Считай!'),
  (gen_random_uuid(), 'imperativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 2, 'DUAL', 'Yuvām manyethām.', 'युवाम् मन्येथाम्।', 'Думайте вдвоем!'),
  (gen_random_uuid(), 'imperativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 2, 'PLURAL', 'Yūyam manyadhvam.', 'यूयम् मन्यध्वम्।', 'Думайте!'),
  (gen_random_uuid(), 'imperativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 3, 'SINGULAR', 'Muniḥ manyatām.', 'मुनिः मन्यताम्।', 'Пусть мудрец размышляет.'),
  (gen_random_uuid(), 'imperativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 3, 'DUAL', 'Munī manyetām.', 'मुनी मन्येताम्।', 'Пусть двое мудрецов размышляют.'),
  (gen_random_uuid(), 'imperativus', 'man', 'मन्', 'думать, считать', 'ATMANEPADA', 3, 'PLURAL', 'Munayaḥ manyantām.', 'मुनयः मन्यन्ताम्।', 'Пусть мудрецы размышляют.');
