-- Flyway migration: create lingua.verbal_endings (DDL + seed data)
-- Hibernate validates this table at startup; it lives in the lingua schema
-- alongside lingua.case_endings.

CREATE SEQUENCE IF NOT EXISTS "lingua"."verbal_endings_id_seq"
    INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1;

CREATE TABLE IF NOT EXISTS "lingua"."verbal_endings" (
    "id" int4 NOT NULL DEFAULT nextval('"lingua".verbal_endings_id_seq'::regclass),
    "ending" varchar(32) NOT NULL,
    "lemma_suffix" varchar(8) NOT NULL DEFAULT '',
    "has_augment" bool NOT NULL DEFAULT false,
    "tense_mood" varchar(20) NOT NULL,
    "person_number" varchar(16) NOT NULL,
    "pada" varchar(8) NOT NULL DEFAULT 'any',
    "notes" varchar(255)
);

CREATE INDEX IF NOT EXISTS "verbal_endings_ending_idx" ON "lingua"."verbal_endings" ("ending");
CREATE INDEX IF NOT EXISTS "verbal_endings_tense_mood_idx" ON "lingua"."verbal_endings" ("tense_mood");
CREATE INDEX IF NOT EXISTS "verbal_endings_person_number_idx" ON "lingua"."verbal_endings" ("person_number");
CREATE INDEX IF NOT EXISTS "verbal_endings_pada_idx" ON "lingua"."verbal_endings" ("pada");

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unq_verbal_ending') THEN
        ALTER TABLE "lingua"."verbal_endings" ADD CONSTRAINT "unq_verbal_ending"
            UNIQUE ("ending", "lemma_suffix", "has_augment", "tense_mood", "person_number", "pada");
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'verbal_endings_pkey') THEN
        ALTER TABLE "lingua"."verbal_endings" ADD CONSTRAINT "verbal_endings_pkey" PRIMARY KEY ("id");
    END IF;
END $$;

ALTER SEQUENCE "lingua"."verbal_endings_id_seq" OWNED BY "lingua"."verbal_endings"."id";

-- Seed data
INSERT INTO "lingua"."verbal_endings" ("ending", "lemma_suffix", "has_augment", "tense_mood", "person_number", "pada", "notes") VALUES
('ati',     'a',   FALSE, 'Present', '3S', 'P', '1/4/6/10 class thematic: bhavati -> bhava'),
('ataH',    'a',   FALSE, 'Present', '3D', 'P', 'bhavataH -> bhava'),
('anti',    'a',   FALSE, 'Present', '3P', 'P', 'bhavanti -> bhava'),
('asi',     'a',   FALSE, 'Present', '2S', 'P', 'bhavasi -> bhava'),
('athaH',   'a',   FALSE, 'Present', '2D', 'P', 'bhavathaH -> bhava'),
('atha',    'a',   FALSE, 'Present', '2P', 'P', 'bhavatha -> bhava'),
('Ami',     'a',   FALSE, 'Present', '1S', 'P', 'bhavAmi -> bhava'),
('AvaH',    'a',   FALSE, 'Present', '1D', 'P', 'bhavAvaH -> bhava'),
('AmaH',    'a',   FALSE, 'Present', '1P', 'P', 'bhavAmaH -> bhava'),
('ti',      '',    FALSE, 'Present', '3S', 'P', 'atti -> ad, asti -> as, dAti -> dA'),
('taH',     '',    FALSE, 'Present', '3D', 'P', 'sthaH -> as, dattaH -> dA'),
('anti',    '',    FALSE, 'Present', '3P', 'P', 'santi -> as'),
('ati',     '',    FALSE, 'Present', '3P', 'P', 'dadati -> dA (3rd class reduplicated)'),
('si',      '',    FALSE, 'Present', '2S', 'P', 'asi -> as'),
('thaH',    '',    FALSE, 'Present', '2D', 'P', 'sthaH -> as'),
('tha',     '',    FALSE, 'Present', '2P', 'P', 'stha -> as'),
('mi',      '',    FALSE, 'Present', '1S', 'P', 'asmi -> as, kurmi -> kR'),
('vaH',     '',    FALSE, 'Present', '1D', 'P', 'svaH -> as'),
('maH',     '',    FALSE, 'Present', '1P', 'P', 'smaH -> as'),
('te',      '',    FALSE, 'Present', '3S', 'A', 'kurute -> kR, datte -> dA'),
('Ate',     '',    FALSE, 'Present', '3D', 'A', 'kurvAte -> kR'),
('ate',     '',    FALSE, 'Present', '3P', 'A', 'kurvate -> kR'),
('se',      '',    FALSE, 'Present', '2S', 'A', 'kuruSe -> kR'),
('Athe',    '',    FALSE, 'Present', '2D', 'A', 'kurvAthe -> kR'),
('dhve',    '',    FALSE, 'Present', '2P', 'A', 'kurudhve -> kR'),
('e',       '',    FALSE, 'Present', '1S', 'A', 'kurve -> kR'),
('vahe',    '',    FALSE, 'Present', '1D', 'A', 'kurvahe -> kR'),
('mahe',    '',    FALSE, 'Present', '1P', 'A', 'kurmahe -> kR'),
('ate',     'a',   FALSE, 'Present', '3S', 'A', 'labhate -> labh, labhyate -> labh (Passive)'),
('ete',     'a',   FALSE, 'Present', '3D', 'A', 'labhete -> labh'),
('ante',    'a',   FALSE, 'Present', '3P', 'A', 'labhante -> labh'),
('ase',     'a',   FALSE, 'Present', '2S', 'A', 'labhase -> labh'),
('ethe',    'a',   FALSE, 'Present', '2D', 'A', 'labhethE -> labh'),
('adhve',   'a',   FALSE, 'Present', '2P', 'A', 'labhadhve -> labh'),
('e',       'a',   FALSE, 'Present', '1S', 'A', 'labhe -> labh'),
('Avahe',   'a',   FALSE, 'Present', '1D', 'A', 'labhAvahe -> labh'),
('Amahe',   'a',   FALSE, 'Present', '1P', 'A', 'labhAmahe -> labh'),
('at',      'a',   TRUE,  'Imperfect', '3S', 'P', 'abhavat -> bhava'),
('atAm',    'a',   TRUE,  'Imperfect', '3D', 'P', 'abhavatAm -> bhava'),
('an',      'a',   TRUE,  'Imperfect', '3P', 'P', 'abhavan -> bhava'),
('aH',      'a',   TRUE,  'Imperfect', '2S', 'P', 'abhavaH -> bhava'),
('atam',    'a',   TRUE,  'Imperfect', '2D', 'P', 'abhavatam -> bhava'),
('ata',     'a',   TRUE,  'Imperfect', '2P', 'P', 'abhavata -> bhava'),
('am',      'a',   TRUE,  'Imperfect', '1S', 'P', 'abhavam -> bhava'),
('Ava',     'a',   TRUE,  'Imperfect', '1D', 'P', 'abhavAva -> bhava'),
('Ama',     'a',   TRUE,  'Imperfect', '1P', 'P', 'abhavAma -> bhava'),
('t',       '',    TRUE,  'Imperfect', '3S', 'P', 'AsIt -> as, adAt -> dA'),
('tAm',     '',    TRUE,  'Imperfect', '3D', 'P', 'AstAm -> as'),
('an',      '',    TRUE,  'Imperfect', '3P', 'P', 'Asan -> as'),
('uH',      '',    TRUE,  'Imperfect', '3P', 'P', 'adur -> dA'),
('H',       '',    TRUE,  'Imperfect', '2S', 'P', 'AsIH -> as'),
('tam',     '',    TRUE,  'Imperfect', '2D', 'P', 'Astam -> as'),
('ta',      '',    TRUE,  'Imperfect', '2P', 'P', 'Asta -> as'),
('am',      '',    TRUE,  'Imperfect', '1S', 'P', 'Asam -> as'),
('va',      '',    TRUE,  'Imperfect', '1D', 'P', 'Asva -> as'),
('ma',      '',    TRUE,  'Imperfect', '1P', 'P', 'Asma -> as'),
('ata',     'a',   TRUE,  'Imperfect', '3S', 'A', 'alabhata -> labh'),
('etAm',    'a',   TRUE,  'Imperfect', '3D', 'A', 'alabhetAm -> labh'),
('anta',    'a',   TRUE,  'Imperfect', '3P', 'A', 'alabhanta -> labh'),
('athAH',   'a',   TRUE,  'Imperfect', '2S', 'A', 'alabhathAH -> labh'),
('ethAm',   'a',   TRUE,  'Imperfect', '2D', 'A', 'alabhethAm -> labh'),
('adhvam',  'a',   TRUE,  'Imperfect', '2P', 'A', 'alabhadhvam -> labh'),
('e',       'a',   TRUE,  'Imperfect', '1S', 'A', 'alabhe -> labh'),
('Avahi',   'a',   TRUE,  'Imperfect', '1D', 'A', 'alabhAvahi -> labh'),
('Amahi',   'a',   TRUE,  'Imperfect', '1P', 'A', 'alabhAmahi -> labh'),
('ta',      '',    TRUE,  'Imperfect', '3S', 'A', 'akuruta -> kR'),
('AtAm',    '',    TRUE,  'Imperfect', '3D', 'A', 'akurvAtAm -> kR'),
('ata',     '',    TRUE,  'Imperfect', '3P', 'A', 'akurvata -> kR'),
('thAH',    '',    TRUE,  'Imperfect', '2S', 'A', 'akurutH -> kR'),
('AthAm',   '',    TRUE,  'Imperfect', '2D', 'A', 'akurvAthAm -> kR'),
('dhvam',   '',    TRUE,  'Imperfect', '2P', 'A', 'akurudhvam -> kR'),
('i',       '',    TRUE,  'Imperfect', '1S', 'A', 'akurvi -> kR'),
('vahi',    '',    TRUE,  'Imperfect', '1D', 'A', 'akurvahi -> kR'),
('mahi',    '',    TRUE,  'Imperfect', '1P', 'A', 'akurmahi -> kR'),
('atu',     'a',   FALSE, 'Imperative', '3S', 'P', 'bhavatu -> bhava'),
('atAm',    'a',   FALSE, 'Imperative', '3D', 'P', 'bhavatAm -> bhava'),
('antu',    'a',   FALSE, 'Imperative', '3P', 'P', 'bhavantu -> bhava'),
('a',       'a',   FALSE, 'Imperative', '2S', 'P', 'bhava -> bhava'),
('atam',    'a',   FALSE, 'Imperative', '2D', 'P', 'bhavatam -> bhava'),
('ata',     'a',   FALSE, 'Imperative', '2P', 'P', 'bhavata -> bhava'),
('Ani',     'a',   FALSE, 'Imperative', '1S', 'P', 'bhavAni -> bhava'),
('Ava',     'a',   FALSE, 'Imperative', '1D', 'P', 'bhavAva -> bhava'),
('Ama',     'a',   FALSE, 'Imperative', '1P', 'P', 'bhavAma -> bhava'),
('atAm',    'a',   FALSE, 'Imperative', '3S', 'A', 'labhatAm -> labh'),
('etAm',    'a',   FALSE, 'Imperative', '3D', 'A', 'labhetAm -> labh'),
('antAm',   'a',   FALSE, 'Imperative', '3P', 'A', 'labhantAm -> labh'),
('asva',    'a',   FALSE, 'Imperative', '2S', 'A', 'labhasva -> labh'),
('ethAm',   'a',   FALSE, 'Imperative', '2D', 'A', 'labhethAm -> labh'),
('adhvam',  'a',   FALSE, 'Imperative', '2P', 'A', 'labhadhvam -> labh'),
('E',       'a',   FALSE, 'Imperative', '1S', 'A', 'labhE -> labh'),
('AvahE',   'a',   FALSE, 'Imperative', '1D', 'A', 'labhavAhE -> labh'),
('AmahE',   'a',   FALSE, 'Imperative', '1P', 'A', 'labhamAhE -> labh'),
('et',      'a',   FALSE, 'Optative', '3S', 'P', 'bhavet -> bhava'),
('etAm',    'a',   FALSE, 'Optative', '3D', 'P', 'bhavetAm -> bhava'),
('eyuH',    'a',   FALSE, 'Optative', '3P', 'P', 'bhaveyuH -> bhava'),
('eH',      'a',   FALSE, 'Optative', '2S', 'P', 'bhaveH -> bhava'),
('etam',    'a',   FALSE, 'Optative', '2D', 'P', 'bhavetam -> bhava'),
('eta',     'a',   FALSE, 'Optative', '2P', 'P', 'bhaveta -> bhava'),
('eyam',    'a',   FALSE, 'Optative', '1S', 'P', 'bhaveyam -> bhava'),
('eva',     'a',   FALSE, 'Optative', '1D', 'P', 'bhaveva -> bhava'),
('ema',     'a',   FALSE, 'Optative', '1P', 'P', 'bhavema -> bhava'),
('eta',     'a',   FALSE, 'Optative', '3S', 'A', 'labheta -> labh'),
('eyAtAm',  'a',   FALSE, 'Optative', '3D', 'A', 'labheyAtAm -> labh'),
('eran',    'a',   FALSE, 'Optative', '3P', 'A', 'labheran -> labh'),
('ethAH',   'a',   FALSE, 'Optative', '2S', 'A', 'labhethAH -> labh'),
('eyAthAm', 'a',   FALSE, 'Optative', '2D', 'A', 'labheyAthAm -> labh'),
('edhvam',  'a',   FALSE, 'Optative', '2P', 'A', 'labhedhvam -> labh'),
('eya',     'a',   FALSE, 'Optative', '1S', 'A', 'labheya -> labh'),
('evahi',   'a',   FALSE, 'Optative', '1D', 'A', 'labhevahi -> labh'),
('emahi',   'a',   FALSE, 'Optative', '1P', 'A', 'labhemahi -> labh'),
('iSyati',  'a',   FALSE, 'Future', '3S', 'P', 'bhaviSyati -> bhava'),
('iSyataH', 'a',   FALSE, 'Future', '3D', 'P', 'bhaviSyataH -> bhava'),
('iSyanti', 'a',   FALSE, 'Future', '3P', 'P', 'bhaviSyanti -> bhava'),
('iSyasi',  'a',   FALSE, 'Future', '2S', 'P', 'bhaviSyasi -> bhava'),
('iSyathaH','a',   FALSE, 'Future', '2D', 'P', 'bhaviSyathaH -> bhava'),
('iSyatha', 'a',   FALSE, 'Future', '2P', 'P', 'bhaviSyatha -> bhava'),
('iSyAmi',  'a',   FALSE, 'Future', '1S', 'P', 'bhaviSyAmi -> bhava'),
('iSyAvaH', 'a',   FALSE, 'Future', '1D', 'P', 'bhaviSyAvaH -> bhava'),
('iSyAmaH', 'a',   FALSE, 'Future', '1P', 'P', 'bhaviSyAmaH -> bhava'),
('Syati',   '',    FALSE, 'Future', '3S', 'P', 'dAsyati -> dA, nekSyati -> nI'),
('SyataH',  '',    FALSE, 'Future', '3D', 'P', 'dAsyataH -> dA'),
('Syanti',  '',    FALSE, 'Future', '3P', 'P', 'dAsyanti -> dA'),
('Syasi',   '',    FALSE, 'Future', '2S', 'P', 'dAsyasi -> dA'),
('SyAmi',   '',    FALSE, 'Future', '1S', 'P', 'dAsyAmi -> dA'),
('iSyate',  'a',   FALSE, 'Future', '3S', 'A', 'bhaviSyate -> bhava'),
('iSyante', 'a',   FALSE, 'Future', '3P', 'A', 'bhaviSyante -> bhava'),
('Syate',   '',    FALSE, 'Future', '3S', 'A', 'dAsyate -> dA'),
('a',       '',    FALSE, 'Perfect', '3S/1S', 'P', 'babhoo-va -> bhoo, tatAna -> tan'),
('atuH',    '',    FALSE, 'Perfect', '3D', 'P', 'babhoovatuH -> bhoo'),
('uH',      '',    FALSE, 'Perfect', '3P', 'P', 'babhoovuH -> bhoo'),
('itha',    '',    FALSE, 'Perfect', '2S', 'P', 'babhoovitha -> bhoo'),
('athaH',   '',    FALSE, 'Perfect', '2D', 'P', 'babhoovathaH -> bhoo'),
('a',       '',    FALSE, 'Perfect', '2P', 'P', 'babhoova -> bhoo'),
('va',      '',    FALSE, 'Perfect', '1D', 'P', 'babhooviva -> bhoo'),
('ma',      '',    FALSE, 'Perfect', '1P', 'P', 'babhoovima -> bhoo'),
('e',       '',    FALSE, 'Perfect', '3S/1S', 'A', 'tenikre -> kR'),
('Ate',     '',    FALSE, 'Perfect', '3D', 'A', 'cakrAte -> kR'),
('ire',     '',    FALSE, 'Perfect', '3P', 'A', 'cakrire -> kR'),
('se',      '',    FALSE, 'Perfect', '2S', 'A', 'cakriSe -> kR'),
('tum',     '',    FALSE, 'Infinitive', 'Inf', 'any', 'gantum -> gam, dAtum -> dA'),
('itum',    '',    FALSE, 'Infinitive', 'Inf', 'any', 'bhavitum -> bhū, likhitum -> likh'),
('tvA',     '',    FALSE, 'Gerund', 'Abs', 'any', 'kRtvA -> kR, gtvA -> gam'),
('itvA',    '',    FALSE, 'Gerund', 'Abs', 'any', 'likhitvA -> likh, bhavitvA -> bhū'),
('ya',      '',    FALSE, 'Gerund', 'Abs_Pref', 'any', 'Agatya -> A-gam, vijitya -> vi-ji'),
('tya',     '',    FALSE, 'Gerund', 'Abs_Pref', 'any', 'kRtya -> kR, srutya -> śru'),
('taH',     '',    FALSE, 'PPP', 'Masc_NomSg', 'any', 'kRtaH -> kR, gataH -> gam'),
('tam',     '',    FALSE, 'PPP', 'Neut_NomSg', 'any', 'kRtam -> kR, gatam -> gam'),
('tA',      '',    FALSE, 'PPP', 'Fem_NomSg', 'any', 'kRtA -> kR, gatA -> gam'),
('itaH',    '',    FALSE, 'PPP', 'Masc_NomSg', 'any', 'likhitaH -> likh'),
('itam',    '',    FALSE, 'PPP', 'Neut_NomSg', 'any', 'likhitam -> likh'),
('itA',     '',    FALSE, 'PPP', 'Fem_NomSg', 'any', 'likhitA -> likh'),
('naH',     '',    FALSE, 'PPP', 'Masc_NomSg', 'any', 'bhinnaH -> bhid, chinnaH -> chid'),
('nam',     '',    FALSE, 'PPP', 'Neut_NomSg', 'any', 'bhinnam -> bhid'),
('nA',      '',    FALSE, 'PPP', 'Fem_NomSg', 'any', 'bhinnA -> bhid'),
('tavAn',   '',    FALSE, 'PPA', 'Masc_NomSg', 'any', 'kRtavAn -> kR, gatavAn -> gam'),
('tavat',   '',    FALSE, 'PPA', 'Neut_NomSg', 'any', 'kRtavat -> kR'),
('tavatI',  '',    FALSE, 'PPA', 'Fem_NomSg', 'any', 'kRtavatI -> kR'),
('itavAn',  '',    FALSE, 'PPA', 'Masc_NomSg', 'any', 'likhitavAn -> likh'),
('an',      'a',   FALSE, 'PPR_Act', 'Masc_NomSg', 'P', 'gacchan -> gam, bhavan -> bhū'),
('at',      'a',   FALSE, 'PPR_Act', 'Neut_NomSg', 'P', 'gacchat -> gam'),
('antI',    'a',   FALSE, 'PPR_Act', 'Fem_NomSg', 'P', 'gacchantI -> gam'),
('mAnaH',   'a',   FALSE, 'PPR_Mid', 'Masc_NomSg', 'A', 'labhamAnaH -> labh, kurvANaH -> kR'),
('mAnam',   'a',   FALSE, 'PPR_Mid', 'Neut_NomSg', 'A', 'labhamAnam -> labh'),
('mAnA',    'a',   FALSE, 'PPR_Mid', 'Fem_NomSg', 'A', 'labhamAnA -> labh'),
('AnaH',    '',    FALSE, 'PPR_Mid', 'Masc_NomSg', 'A', 'kurvAnaH -> kR, dadAnaH -> dA'),
('tavyaH',  '',    FALSE, 'Gerundive', 'Masc_NomSg', 'any', 'kartavyaH -> kR, bhavitavyaH -> bhū'),
('tavyam',  '',    FALSE, 'Gerundive', 'Neut_NomSg', 'any', 'kartavyam -> kR'),
('tavyA',   '',    FALSE, 'Gerundive', 'Fem_NomSg', 'any', 'kartavyA -> kR'),
('anIyaH',  '',    FALSE, 'Gerundive', 'Masc_NomSg', 'any', 'karaNIyaH -> kR, bhavanIyaH -> bhū'),
('anIyam',  '',    FALSE, 'Gerundive', 'Neut_NomSg', 'any', 'karaNIyam -> kR'),
('anIyA',   '',    FALSE, 'Gerundive', 'Fem_NomSg', 'any', 'karaNIyA -> kR'),
('yaH',     '',    FALSE, 'Gerundive', 'Masc_NomSg', 'any', 'kAryaH -> kR, jñeyaH -> jñā'),
('yam',     '',    FALSE, 'Gerundive', 'Neut_NomSg', 'any', 'kAryam -> kR'),
('yA',      '',    FALSE, 'Gerundive', 'Fem_NomSg', 'any', 'kAryA -> kR')
ON CONFLICT DO NOTHING;

SELECT setval('"lingua"."verbal_endings_id_seq"', 220, true);