server:
  port: ${API_GATEWAY_PORT}

spring:
  application:
    name: api-gateway
  config:
    import: "optional:file:.env[.properties]"
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}
          predicates:
            - Path=/api/v1/auth/**
        - id: content-service
          uri: http://${CONTENT_SERVICE_HOST}:${CONTENT_SERVICE_PORT}
          predicates:
            - Path=/api/v1/content/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    root: INFO
    sm.selflearn.samskrtam: DEBUG
    org.springframework.security: TRACE
