apiVersion: v1
kind: Service
metadata:
  name: mailpit-smtp
  namespace: mail-system
spec:
  type: LoadBalancer
  selector:
    app: mailpit
  ports:
    - name: smtp
      protocol: TCP
      port: 25
      targetPort: 1025
  loadBalancerIP: 192.168.162.239