package sm.selflearn.samskrtam.curriculum.questitem;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import sm.selflearn.samskrtam.quest.AnswerMode;

import java.time.Instant;
import java.util.UUID;

/**
 * Materialized quest item generated by a batch-owner for any quest type.
 * Generic table: type-specific data lives in {@code payload}/{@code distractors}
 * as (pre-serialized) JSONB. See curriculum-quest-items.md §1.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "quest_item", schema = "curriculum")
public class QuestItem {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "topic_id", nullable = false)
    private UUID topicId;

    @Column(name = "item_type", nullable = false, length = 40)
    private String itemType;

    @Enumerated(EnumType.STRING)
    @Column(name = "answer_mode", nullable = false, length = 20)
    private AnswerMode answerMode;

    @Column(name = "prompt", nullable = false)
    private String prompt;

    @Column(name = "prompt_ru")
    private String promptRu;

    @Column(name = "correct_answer", length = 200)
    private String correctAnswer;

    @Column(name = "correct_answer_ru", length = 200)
    private String correctAnswerRu;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "distractors", nullable = false, columnDefinition = "jsonb")
    private String distractors;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "distractors_ru", columnDefinition = "jsonb")
    private String distractorsRu;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "payload", nullable = false, columnDefinition = "jsonb")
    private String payload;

    @Column(name = "generator_source", nullable = false, length = 60)
    private String generatorSource;

    @Column(name = "progress_tag", length = 255)
    private String progressTag;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @PrePersist
    void onCreate() {
        createdAt = Instant.now();
    }
}