server:
  port: ${DICTIONARY_SERVICE_PORT}

spring:
  application:
    name: dictionary-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: cologne_mw
  flyway:
    enabled: false # Monier-Williams DB is static, no migrations needed
    schemas: cologne_mw

logging:
  level:
    root: WARN
    sm.selflearn.samskrtam: DEBUG

management:
  server:
    port: ${DICTIONARY_MANAGEMENT_PORT}
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true