server:
  port: 8085

spring:
  application:
    name: dictionary-service
  r2dbc:
    # Defined by env var in docker-compose.yml
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/samskrtam?schema=dictionary}
    username: ${DB_USER:samskrtam}
    password: ${DB_PASSWORD:samskrtam}
  flyway:
    # Flyway uses JDBC, so we configure it separately
    url: jdbc:postgresql://localhost:5432/samskrtam
    schemas: dictionary
    user: ${DB_USER:samskrtam}
    password: ${DB_PASSWORD:samskrtam}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/samskrtam}
