-- Seed of 70 atomic GRAMMAR topics (L0-L6) + 2 evergreen topics, replacing the
-- earlier ~20-topic coarse model. See curriculum.md §2 for the source table.
-- English titleEn left equal to a transliteration-friendly label where no
-- separate English title was specified; adjust during content review.

INSERT INTO curriculum.topic (id, code, title_ru, title_en, learning_level, domain, is_evergreen) VALUES
    (gen_random_uuid(), 'deva-svara', 'Devanāgarī: svara — гласные', 'Devanāgarī: svara — гласные', 'L0', 'GRAMMAR', false),
    (gen_random_uuid(), 'deva-vyanjana', 'Devanāgarī: vyañjana — согласные', 'Devanāgarī: vyañjana — согласные', 'L0', 'GRAMMAR', false),
    (gen_random_uuid(), 'matra-conjuncts', 'Mātrā и сочетание согласных с гласными', 'Mātrā и сочетание согласных с гласными', 'L0', 'GRAMMAR', false),
    (gen_random_uuid(), 'deva-diacritics', 'Anusvāra, visarga, chandrabindu', 'Anusvāra, visarga, chandrabindu', 'L0', 'GRAMMAR', false),
    (gen_random_uuid(), 'articulation-places', 'Места и способы артикуляции', 'Места и способы артикуляции', 'L0', 'GRAMMAR', false),
    (gen_random_uuid(), 'vowel-length-oppositions', 'Долгие/краткие гласные и фонетические оппозиции', 'Долгие/краткие гласные и фонетические оппозиции', 'L0', 'GRAMMAR', false),
    (gen_random_uuid(), 'basic-function-words', 'Базовые служебные слова', 'Базовые служебные слова', 'L0', 'GRAMMAR', false),
    (gen_random_uuid(), 'basic-vocabulary-core', 'Базовая лексика: человек, предметы, действия', 'Базовая лексика: человек, предметы, действия', 'L0', 'GRAMMAR', false),
    (gen_random_uuid(), 'sandhi-vowels-external', 'Sandhi: внешние гласные', 'Sandhi: внешние гласные', 'L1', 'GRAMMAR', false),
    (gen_random_uuid(), 'sandhi-consonants', 'Sandhi: согласные', 'Sandhi: согласные', 'L1', 'GRAMMAR', false),
    (gen_random_uuid(), 'sandhi-visarga', 'Sandhi: visarga', 'Sandhi: visarga', 'L1', 'GRAMMAR', false),
    (gen_random_uuid(), 'stem-case-concept', 'Понятие основы, окончания и падежа', 'Понятие основы, окончания и падежа', 'L1', 'GRAMMAR', false),
    (gen_random_uuid(), 'a-stem-masc', 'a-основа: masculine', 'a-основа: masculine', 'L1', 'GRAMMAR', false),
    (gen_random_uuid(), 'a-stem-neut', 'a-основа: neuter', 'a-основа: neuter', 'L1', 'GRAMMAR', false),
    (gen_random_uuid(), 'a-stem-fem', 'ā-основа: feminine', 'ā-основа: feminine', 'L1', 'GRAMMAR', false),
    (gen_random_uuid(), 'case-meanings-basic', 'Основные падежные значения', 'Основные падежные значения', 'L1', 'GRAMMAR', false),
    (gen_random_uuid(), 'personal-pronouns', 'Личные местоимения', 'Личные местоимения', 'L1', 'GRAMMAR', false),
    (gen_random_uuid(), 'pronoun-stems-declension', 'Основы местоимений и их падежные формы', 'Основы местоимений и их падежные формы', 'L1', 'GRAMMAR', false),
    (gen_random_uuid(), 'verb-root-stem-ending', 'Корень, основа и личное окончание', 'Корень, основа и личное окончание', 'L1', 'GRAMMAR', false),
    (gen_random_uuid(), 'present-parasmaipada-formation', 'Present parasmaipada: формирование', 'Present parasmaipada: формирование', 'L2', 'GRAMMAR', false),
    (gen_random_uuid(), 'present-parasmaipada-usage', 'Present parasmaipada: употребление', 'Present parasmaipada: употребление', 'L2', 'GRAMMAR', false),
    (gen_random_uuid(), 'present-atmanepada', 'Present ātmanepada', 'Present ātmanepada', 'L2', 'GRAMMAR', false),
    (gen_random_uuid(), 'i-u-stems', 'i/u-основы', 'i/u-основы', 'L2', 'GRAMMAR', false),
    (gen_random_uuid(), 'r-stems', 'ṛ-основы', 'ṛ-основы', 'L2', 'GRAMMAR', false),
    (gen_random_uuid(), 'demonstrative-pronouns', 'Указательные местоимения', 'Указательные местоимения', 'L2', 'GRAMMAR', false),
    (gen_random_uuid(), 'interrogative-pronouns', 'Вопросительные местоимения', 'Вопросительные местоимения', 'L2', 'GRAMMAR', false),
    (gen_random_uuid(), 'relative-pronouns', 'Относительные местоимения', 'Относительные местоимения', 'L2', 'GRAMMAR', false),
    (gen_random_uuid(), 'noun-adjective-agreement', 'Согласование существительного и определения', 'Согласование существительного и определения', 'L2', 'GRAMMAR', false),
    (gen_random_uuid(), 'simple-sentence-svo', 'Простое предложение: субъект → объект → глагол', 'Простое предложение: субъект → объект → глагол', 'L2', 'GRAMMAR', false),
    (gen_random_uuid(), 'numerals-1-4', 'Числительные 1–4', 'Числительные 1–4', 'L3', 'GRAMMAR', false),
    (gen_random_uuid(), 'numerals-5-10', 'Числительные 5–10', 'Числительные 5–10', 'L3', 'GRAMMAR', false),
    (gen_random_uuid(), 'numeral-agreement', 'Числительные и согласование', 'Числительные и согласование', 'L3', 'GRAMMAR', false),
    (gen_random_uuid(), 'imperfect', 'Imperfect', 'Imperfect', 'L3', 'GRAMMAR', false),
    (gen_random_uuid(), 'future', 'Future', 'Future', 'L3', 'GRAMMAR', false),
    (gen_random_uuid(), 'verb-root-classes-overview', 'Основные классы глагольных корней', 'Основные классы глагольных корней', 'L3', 'GRAMMAR', false),
    (gen_random_uuid(), 'present-active-participle', 'Present active participle', 'Present active participle', 'L3', 'GRAMMAR', false),
    (gen_random_uuid(), 'past-passive-participle', 'Past passive participle', 'Past passive participle', 'L3', 'GRAMMAR', false),
    (gen_random_uuid(), 'absolutive-ktva', 'Absolutives: ktvā', 'Absolutives: ktvā', 'L3', 'GRAMMAR', false),
    (gen_random_uuid(), 'absolutive-ya', 'Absolutives: -ya', 'Absolutives: -ya', 'L3', 'GRAMMAR', false),
    (gen_random_uuid(), 'karaka-semantic-roles', 'Kāraka и семантические роли', 'Kāraka и семантические роли', 'L3', 'GRAMMAR', false),
    (gen_random_uuid(), 'case-as-karaka', 'Падежи в роли kāraka', 'Падежи в роли kāraka', 'L3', 'GRAMMAR', false),
    (gen_random_uuid(), 'perfect', 'Perfect', 'Perfect', 'L4', 'GRAMMAR', false),
    (gen_random_uuid(), 'aorist', 'Aorist', 'Aorist', 'L4', 'GRAMMAR', false),
    (gen_random_uuid(), 'imperative', 'Imperative', 'Imperative', 'L4', 'GRAMMAR', false),
    (gen_random_uuid(), 'optative', 'Optative', 'Optative', 'L4', 'GRAMMAR', false),
    (gen_random_uuid(), 'participle-past-active', 'Participles: past active', 'Participles: past active', 'L4', 'GRAMMAR', false),
    (gen_random_uuid(), 'participle-future', 'Participles: future', 'Participles: future', 'L4', 'GRAMMAR', false),
    (gen_random_uuid(), 'participial-constructions', 'Participial constructions', 'Participial constructions', 'L4', 'GRAMMAR', false),
    (gen_random_uuid(), 'irregular-stems-declension', 'Сложные основы и нестандартные склонения', 'Сложные основы и нестандартные склонения', 'L4', 'GRAMMAR', false),
    (gen_random_uuid(), 'relative-constructions', 'Relative constructions', 'Relative constructions', 'L4', 'GRAMMAR', false),
    (gen_random_uuid(), 'correlative-constructions', 'Correlative constructions', 'Correlative constructions', 'L4', 'GRAMMAR', false),
    (gen_random_uuid(), 'complex-noun-phrases', 'Сложные именные группы', 'Сложные именные группы', 'L4', 'GRAMMAR', false),
    (gen_random_uuid(), 'compound-words-basics', 'Compound words: основы', 'Compound words: основы', 'L5', 'GRAMMAR', false),
    (gen_random_uuid(), 'tatpurusha', 'Tatpuruṣa', 'Tatpuruṣa', 'L5', 'GRAMMAR', false),
    (gen_random_uuid(), 'karmadharaya', 'Karmadhāraya', 'Karmadhāraya', 'L5', 'GRAMMAR', false),
    (gen_random_uuid(), 'bahuvrihi', 'Bahuvrīhi', 'Bahuvrīhi', 'L5', 'GRAMMAR', false),
    (gen_random_uuid(), 'dvandva', 'Dvandva', 'Dvandva', 'L5', 'GRAMMAR', false),
    (gen_random_uuid(), 'derivation-tva-ta', 'Derivation: -tva, -ta', 'Derivation: -tva, -ta', 'L5', 'GRAMMAR', false),
    (gen_random_uuid(), 'derivation-in-vant-mat', 'Derivation: -in, -vant, -mat', 'Derivation: -in, -vant, -mat', 'L5', 'GRAMMAR', false),
    (gen_random_uuid(), 'conditional-constructions', 'Conditional constructions', 'Conditional constructions', 'L5', 'GRAMMAR', false),
    (gen_random_uuid(), 'reported-speech', 'Reported speech / indirect constructions', 'Reported speech / indirect constructions', 'L5', 'GRAMMAR', false),
    (gen_random_uuid(), 'complex-subordinate-clauses', 'Complex subordinate clauses', 'Complex subordinate clauses', 'L5', 'GRAMMAR', false),
    (gen_random_uuid(), 'complex-sandhi-combinations', 'Сложные sandhi-комбинации', 'Сложные sandhi-комбинации', 'L6', 'GRAMMAR', false),
    (gen_random_uuid(), 'irregular-rare-forms', 'Редкие и нерегулярные формы', 'Редкие и нерегулярные формы', 'L6', 'GRAMMAR', false),
    (gen_random_uuid(), 'complex-verb-constructions', 'Сложные глагольные конструкции', 'Сложные глагольные конструкции', 'L6', 'GRAMMAR', false),
    (gen_random_uuid(), 'absolute-constructions', 'Абсолютные конструкции', 'Абсолютные конструкции', 'L6', 'GRAMMAR', false),
    (gen_random_uuid(), 'complex-relative-constructions', 'Сложные относительные конструкции', 'Сложные относительные конструкции', 'L6', 'GRAMMAR', false),
    (gen_random_uuid(), 'poetic-word-order', 'Поэтический порядок слов', 'Поэтический порядок слов', 'L6', 'GRAMMAR', false),
    (gen_random_uuid(), 'ellipsis-implied-forms', 'Эллипсис и подразумеваемые формы', 'Эллипсис и подразумеваемые формы', 'L6', 'GRAMMAR', false),
    (gen_random_uuid(), 'syntactic-analysis-of-text', 'Синтаксический разбор оригинального текста', 'Синтаксический разбор оригинального текста', 'L6', 'GRAMMAR', false),
    (gen_random_uuid(), 'mixed-review', 'Mixed review', 'Mixed review', 'L0', 'GRAMMAR', true),
    (gen_random_uuid(), 'error-correction', 'Error correction', 'Error correction', 'L0', 'GRAMMAR', true);

-- Prerequisite edges (RECOMMENDED strength, see curriculum.md §1)
INSERT INTO curriculum.topic_prerequisite (topic_id, prerequisite_topic_id, strength)
SELECT t.id, p.id, 'RECOMMENDED'
FROM (VALUES
    ('deva-vyanjana', 'deva-svara'),
    ('matra-conjuncts', 'deva-vyanjana'),
    ('deva-diacritics', 'matra-conjuncts'),
    ('articulation-places', 'deva-vyanjana'),
    ('vowel-length-oppositions', 'deva-svara'),
    ('basic-vocabulary-core', 'basic-function-words'),
    ('sandhi-vowels-external', 'deva-svara'),
    ('sandhi-consonants', 'sandhi-vowels-external'),
    ('sandhi-visarga', 'sandhi-consonants'),
    ('sandhi-visarga', 'deva-diacritics'),
    ('stem-case-concept', 'basic-vocabulary-core'),
    ('a-stem-masc', 'stem-case-concept'),
    ('a-stem-neut', 'a-stem-masc'),
    ('a-stem-fem', 'a-stem-masc'),
    ('case-meanings-basic', 'a-stem-masc'),
    ('personal-pronouns', 'a-stem-masc'),
    ('pronoun-stems-declension', 'personal-pronouns'),
    ('verb-root-stem-ending', 'basic-vocabulary-core'),
    ('present-parasmaipada-formation', 'verb-root-stem-ending'),
    ('present-parasmaipada-usage', 'present-parasmaipada-formation'),
    ('present-atmanepada', 'present-parasmaipada-formation'),
    ('i-u-stems', 'a-stem-neut'),
    ('i-u-stems', 'a-stem-fem'),
    ('r-stems', 'i-u-stems'),
    ('demonstrative-pronouns', 'pronoun-stems-declension'),
    ('interrogative-pronouns', 'pronoun-stems-declension'),
    ('relative-pronouns', 'demonstrative-pronouns'),
    ('noun-adjective-agreement', 'a-stem-fem'),
    ('noun-adjective-agreement', 'case-meanings-basic'),
    ('simple-sentence-svo', 'present-parasmaipada-usage'),
    ('simple-sentence-svo', 'noun-adjective-agreement'),
    ('numerals-1-4', 'demonstrative-pronouns'),
    ('numerals-5-10', 'numerals-1-4'),
    ('numeral-agreement', 'numerals-5-10'),
    ('numeral-agreement', 'noun-adjective-agreement'),
    ('imperfect', 'present-parasmaipada-usage'),
    ('future', 'present-parasmaipada-usage'),
    ('verb-root-classes-overview', 'present-atmanepada'),
    ('present-active-participle', 'present-parasmaipada-formation'),
    ('past-passive-participle', 'verb-root-classes-overview'),
    ('absolutive-ktva', 'present-parasmaipada-usage'),
    ('absolutive-ya', 'absolutive-ktva'),
    ('karaka-semantic-roles', 'simple-sentence-svo'),
    ('case-as-karaka', 'karaka-semantic-roles'),
    ('perfect', 'imperfect'),
    ('aorist', 'imperfect'),
    ('imperative', 'present-parasmaipada-usage'),
    ('optative', 'present-parasmaipada-usage'),
    ('participle-past-active', 'past-passive-participle'),
    ('participle-future', 'future'),
    ('participle-future', 'present-active-participle'),
    ('participial-constructions', 'participle-past-active'),
    ('participial-constructions', 'karaka-semantic-roles'),
    ('irregular-stems-declension', 'r-stems'),
    ('relative-constructions', 'relative-pronouns'),
    ('relative-constructions', 'case-as-karaka'),
    ('correlative-constructions', 'relative-constructions'),
    ('complex-noun-phrases', 'noun-adjective-agreement'),
    ('complex-noun-phrases', 'irregular-stems-declension'),
    ('compound-words-basics', 'complex-noun-phrases'),
    ('tatpurusha', 'compound-words-basics'),
    ('karmadharaya', 'compound-words-basics'),
    ('bahuvrihi', 'compound-words-basics'),
    ('dvandva', 'compound-words-basics'),
    ('derivation-tva-ta', 'past-passive-participle'),
    ('derivation-in-vant-mat', 'derivation-tva-ta'),
    ('conditional-constructions', 'optative'),
    ('conditional-constructions', 'correlative-constructions'),
    ('reported-speech', 'simple-sentence-svo'),
    ('complex-subordinate-clauses', 'correlative-constructions'),
    ('complex-subordinate-clauses', 'participial-constructions'),
    ('complex-sandhi-combinations', 'sandhi-visarga'),
    ('irregular-rare-forms', 'irregular-stems-declension'),
    ('irregular-rare-forms', 'perfect'),
    ('complex-verb-constructions', 'aorist'),
    ('complex-verb-constructions', 'optative'),
    ('absolute-constructions', 'participial-constructions'),
    ('complex-relative-constructions', 'correlative-constructions'),
    ('poetic-word-order', 'complex-subordinate-clauses'),
    ('ellipsis-implied-forms', 'poetic-word-order'),
    ('syntactic-analysis-of-text', 'ellipsis-implied-forms'),
    ('syntactic-analysis-of-text', 'complex-verb-constructions')
) AS e(topic_code, prerequisite_code)
JOIN curriculum.topic t ON t.code = e.topic_code AND t.domain = 'GRAMMAR'
JOIN curriculum.topic p ON p.code = e.prerequisite_code AND p.domain = 'GRAMMAR';
