server:
  port: ${STATISTICS_SERVICE_PORT}

spring:
  application:
    name: statistics-service
  config:
    import: "optional:file:.env[.properties]"
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}?currentSchema=statistics
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    url: ${SPRING_DATASOURCE_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    schemas: statistics

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: sm.selflearn.samskrtam.kafka.serialization.SamskrtamJsonSerializer
      properties:
        spring.json.add.type.headers: true # Добавляем информацию о типе в заголовки
        security.protocol: PLAINTEXT
        listener.name: EXTERNAL
    consumer: # Добавляем конфигурацию потребителя для консистентности
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: sm.selflearn.samskrtam.kafka.serialization.SamskrtamJsonDeserializer
      properties:
        security.protocol: PLAINTEXT
        listener.name: EXTERNAL
    streams:
      application-id: statistics-service-application # Уникальный ID для Kafka Streams приложения
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      properties:
        state.dir: /tmp/kafka-streams # Директория для хранения состояния Kafka Streams
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde # Используем JsonSerde по умолчанию
        spring.json.value.default.type: sm.selflearn.samskrtam.quiz.event.StatisticEvent # Указываем тип по умолчанию для десериализации
        spring.json.trusted.packages: "sm.selflearn.samskrtam.*" # Доверяем всем пакетам приложения

management:
  endpoints:
    web:
      exposure:
        include: ""
  tracing:
    enabled: false

logging:
  level:
    root: WARN
    sm.selflearn.samskrtam: DEBUG
