export const NUMBER_TYPES = ['SINGULAR', 'DUAL', 'PLURAL'] as const;

export const CASE_TYPES = [
  'NOMINATIVE', 'ACCUSATIVE', 'INSTRUMENTAL', 'DATIVE',
  'ABLATIVE', 'GENITIVE', 'LOCATIVE', 'VOCATIVE',
] as const;